import type { GameState, LineupDraft, Team, TeamControlMode } from "@/lib/data/olyDataTypes";
import { buildAiLegacyLineupPreview } from "@/lib/ai/ai-legacy-lineup-engine";
import { createDefaultLineupDraftModifiers } from "@/lib/lineups/legacy-lineup-modifiers";
import { createLineupDraftId } from "@/lib/lineups/lineup-discipline-contract";
import { loadLocalLegacyLineupContextFromGameState } from "@/lib/lineups/legacy-lineup-local-service";
import type { LegacyLineupEntryInput, LegacyLineupKeyParams, LegacyLineupLoadedContext } from "@/lib/lineups/legacy-lineup-types";
import { buildLegacyMatchdayReadiness } from "@/lib/lineups/legacy-matchday-readiness";
import { validateLegacyLineupContext } from "@/lib/lineups/legacy-lineup-validator";
import { createPersistenceService } from "@/lib/persistence/persistence-service";
import type { PersistedSaveGame, PersistenceService } from "@/lib/persistence/types";
import {
  APPLY_CONFIRM_TOKEN as RESULT_APPLY_CONFIRM_TOKEN,
  LegacyMatchdayResultApplyService,
  prepareLegacyMatchdayResultApply,
} from "@/lib/resolve/legacy-matchday-result-apply-service";
import { STANDINGS_APPLY_CONFIRM_TOKEN, executeStandingsApply } from "@/lib/standings/standings-apply-service";
import { getTeamStrategyProfile } from "@/lib/foundation/team-strategy-profiles";
import { refreshTeamObjectiveState } from "@/lib/board/team-season-objectives-service";

export const MATCHDAY_MVP_SCORING_CONFIRM_TOKEN = "RUN_MATCHDAY_MVP_SCORING";

export type MatchdayMvpLineupStatus =
  | "existing_lineup"
  | "auto_lineup_source"
  | "blocked_underfilled_roster"
  | "blocked_missing_scores"
  | "blocked_invalid_auto_lineup"
  | "blocked_missing_matchday_contract";

export type MatchdayMvpLineupTeam = {
  teamId: string;
  teamCode: string;
  teamName: string;
  controlMode: TeamControlMode;
  readinessBefore: string;
  rosterCount: number;
  requiredPlayers: number;
  targetRosterSize: number | null;
  targetSource: "team_identity_player_opt" | "strategy_profile_roster_opt" | "target_roster_size_missing";
  status: MatchdayMvpLineupStatus;
  autoGenerated: boolean;
  warnings: string[];
  blockingReasons: string[];
};

export type MatchdayMvpScoreboardRow = {
  teamId: string;
  teamName: string;
  baseScore: number;
  formCardStatus: "ready" | "missing_source";
  formCardLabel: string | null;
  formCardModifier: number | null;
  mutatorMode: "legacy_selected_traits" | "mvp_forced_mutators";
  mutator1Label: string | null;
  mutator1Modifier: number | null;
  mutator2Label: string | null;
  mutator2Modifier: number | null;
  captainStatus: "mapped" | "missing_source";
  captainModifier: number | null;
  fatigueStatus: "mapped" | "missing_source";
  fatigueModifier: number | null;
  teamPpsStatus: "ready" | "missing_source";
  teamPpsModifier: number | null;
  score: number;
  rank: number;
  points: number | null;
  status: string;
  autoLineupSource: boolean;
  warnings: string[];
};

export type MatchdayMvpTopPlayerRow = {
  disciplineSide: "d1" | "d2";
  disciplineId: string;
  disciplineName: string;
  playerId: string;
  playerName: string;
  teamId: string;
  teamName: string;
  finalPlayerScore: number;
  pointsAwarded: number | null;
  mutatorPpsBonus: number | null;
  mutatorScoreBonus: number | null;
  rankInDiscipline: number;
};

export type MatchdayMvpScoringResult = {
  source: "sqlite";
  dryRun: boolean;
  executed: boolean;
  status: "ready" | "warning" | "blocked" | "applied";
  scope: {
    saveId: string;
    seasonId: string;
    matchdayId: string;
  };
  targetMatchday: {
    matchdayId: string;
    label: string;
    d1DisciplineId: string | null;
    d1DisciplineName: string | null;
    d2DisciplineId: string | null;
    d2DisciplineName: string | null;
  };
  rosterGate: {
    teamsBelowMinimum: number;
    teamsBelowTarget: number;
    teamsMissingTarget: number;
    warnings: string[];
  };
  lineupSummary: {
    totalTeams: number;
    existingLineups: number;
    autoGeneratedLineups: number;
    blockedTeams: number;
  };
  resolveSources: {
    formCardSourceStatus: "ready" | "missing_source";
    formCardSourceLabel: string | null;
    mutatorSourceStatus: "ready" | "missing_source";
    mutatorSourceLabel: string | null;
    captainSourceStatus: "mapped" | "missing_source";
    fatigueSourceStatus: "mapped" | "missing_source";
    teamPpsSourceStatus: "ready" | "missing_source";
  };
  lineupTeams: MatchdayMvpLineupTeam[];
  resolveStatus: string;
  mutatorMode: "mvp_forced_mutators";
  d1Scoreboard: MatchdayMvpScoreboardRow[];
  d2Scoreboard: MatchdayMvpScoreboardRow[];
  d1TopPlayers: MatchdayMvpTopPlayerRow[];
  d2TopPlayers: MatchdayMvpTopPlayerRow[];
  ppWinners: MatchdayMvpTopPlayerRow[];
  totalTeamsScored: number;
  resultApply: {
    applied: boolean;
    matchdayResultId: string | null;
    replacedExisting: boolean;
  };
  standingsApply: {
    applied: boolean;
    auditLogId: string | null;
  };
  warnings: string[];
  blockingReasons: string[];
};

const MATCHDAY_MINIMUM_PLAYERS = 7;

function buildRosterGate(lineupTeams: MatchdayMvpLineupTeam[], rosterWarnings: string[]) {
  return {
    teamsBelowMinimum: lineupTeams.filter((team) => team.status === "blocked_underfilled_roster").length,
    teamsBelowTarget: rosterWarnings.filter((warning) => warning.includes("below_planning_target")).length,
    teamsMissingTarget: rosterWarnings.filter((warning) => warning.includes("target_roster_size_missing")).length,
    warnings: rosterWarnings,
  };
}

export type MatchdayMvpScoringParams = {
  source?: "sqlite" | "prisma";
  saveId: string;
  seasonId: string;
  matchdayId?: string | null;
  dryRun?: boolean;
  execute?: boolean;
  confirmToken?: string | null;
  forceReplace?: boolean;
};

function resolveStrictLocalSave(persistence: PersistenceService, saveId: string): PersistedSaveGame {
  const save = persistence.getSaveById(saveId);
  if (!save) {
    throw new Error(`Requested local save ${saveId} could not be loaded for matchday MVP scoring.`);
  }
  return save;
}

function resolveTargetRoster(team: Team, gameState: GameState) {
  const teamIdentity = gameState.teamIdentities.find((entry) => entry.teamId === team.teamId) ?? null;
  if (teamIdentity && Number.isFinite(teamIdentity.playerOpt) && teamIdentity.playerOpt > 0) {
    return {
      targetRosterSize: Math.round(teamIdentity.playerOpt),
      targetSource: "team_identity_player_opt" as const,
    };
  }

  const strategyProfile = getTeamStrategyProfile(gameState, team.teamId);
  if (strategyProfile?.rosterOptTarget != null && Number.isFinite(strategyProfile.rosterOptTarget) && strategyProfile.rosterOptTarget > 0) {
    return {
      targetRosterSize: Math.round(strategyProfile.rosterOptTarget),
      targetSource: "strategy_profile_roster_opt" as const,
    };
  }

  return {
    targetRosterSize: null,
    targetSource: "target_roster_size_missing" as const,
  };
}

function buildDisciplineSidePlayerCounts(context: LegacyLineupLoadedContext) {
  const result: Record<string, number> = {};
  const d1 = context.matchdayContract?.discipline1;
  const d2 = context.matchdayContract?.discipline2;
  if (d1?.requiredPlayers != null) {
    result[`${d1.disciplineId}::d1`] = d1.requiredPlayers;
  }
  if (d2?.requiredPlayers != null) {
    result[`${d2.disciplineId}::d2`] = d2.requiredPlayers;
  }
  return result;
}

function upsertDraftInGameState(
  gameState: GameState,
  params: LegacyLineupKeyParams,
  entries: LegacyLineupEntryInput[],
) {
  const now = new Date().toISOString();
  const lineupId = createLineupDraftId(params);
  const existingDrafts = gameState.seasonState.lineupDrafts ?? [];
  const existing = existingDrafts.find((draft) => draft.lineupId === lineupId) ?? null;
  const nextDraft: LineupDraft = {
    lineupId,
    saveId: params.saveId,
    seasonId: params.seasonId,
    matchdayId: params.matchdayId,
    teamId: params.teamId,
    status: "draft",
    entries: entries.map((entry) => ({ ...entry })),
    modifiers: existing?.modifiers ?? createDefaultLineupDraftModifiers(),
    createdAt: existing?.createdAt ?? now,
    updatedAt: now,
  };

  return {
    ...gameState,
    seasonState: {
      ...gameState.seasonState,
      lineupDrafts: [
        ...existingDrafts.filter((draft) => draft.lineupId !== lineupId),
        nextDraft,
      ],
    },
  };
}

function buildContextsFromGameState(gameState: GameState, scope: { saveId: string; seasonId: string; matchdayId: string }) {
  return [...gameState.teams]
    .sort((left, right) => left.teamId.localeCompare(right.teamId))
    .map((team) =>
      loadLocalLegacyLineupContextFromGameState(gameState, {
        saveId: scope.saveId,
        seasonId: scope.seasonId,
        matchdayId: scope.matchdayId,
        teamId: team.teamId,
      }),
    );
}

function buildScoreboardRow(
  teamResult: NonNullable<Awaited<ReturnType<typeof prepareLegacyMatchdayResultApply>>["preview"]["disciplinePreviews"]>[number]["teamResults"][number],
  autoLineupTeamIds: Set<string>,
): MatchdayMvpScoreboardRow {
  const mutator1 = teamResult.mutatorSlots[0] ?? null;
  const mutator2 = teamResult.mutatorSlots[1] ?? null;
  return {
    teamId: teamResult.teamId,
    teamName: teamResult.teamName,
    baseScore: teamResult.baseScore,
    formCardStatus: teamResult.formCardStatus,
    formCardLabel: teamResult.formCardLabel,
    formCardModifier: teamResult.formModifier,
    mutatorMode: teamResult.mutatorMode,
    mutator1Label: mutator1?.label ?? null,
    mutator1Modifier: mutator1?.scoreModifier ?? null,
    mutator2Label: mutator2?.label ?? null,
    mutator2Modifier: mutator2?.scoreModifier ?? null,
    captainStatus: teamResult.captainStatus,
    captainModifier: teamResult.captainBonus,
    fatigueStatus: teamResult.fatigueStatus,
    fatigueModifier: teamResult.fatigueModifier,
    teamPpsStatus: teamResult.teamPpsStatus,
    teamPpsModifier: teamResult.teamPpsModifier,
    score: teamResult.finalPreviewScore,
    rank: teamResult.rank,
    points: teamResult.teamPoints,
    status: teamResult.status,
    autoLineupSource: autoLineupTeamIds.has(teamResult.teamId),
    warnings: teamResult.warnings,
  };
}

function buildTopPlayerRow(
  disciplinePreview: NonNullable<Awaited<ReturnType<typeof prepareLegacyMatchdayResultApply>>["preview"]["disciplinePreviews"]>[number],
  player: NonNullable<Awaited<ReturnType<typeof prepareLegacyMatchdayResultApply>>["preview"]["disciplinePreviews"]>[number]["topPlayers"][number],
): MatchdayMvpTopPlayerRow {
  const teamResult = disciplinePreview.teamResults.find((entry) => entry.teamId === player.teamId) ?? null;
  return {
    disciplineSide: disciplinePreview.disciplineSide,
    disciplineId: disciplinePreview.disciplineId,
    disciplineName: disciplinePreview.disciplineName,
    playerId: player.playerId,
    playerName: player.playerName,
    teamId: player.teamId,
    teamName: teamResult?.teamName ?? player.teamId,
    finalPlayerScore: player.finalPlayerScore,
    pointsAwarded: player.pointsAwarded,
    mutatorPpsBonus: player.mutatorPpsBonus ?? null,
    mutatorScoreBonus: player.mutatorBonus ?? null,
    rankInDiscipline: player.rankInDiscipline,
  };
}

function buildResolveSources(
  context: LegacyLineupLoadedContext,
  d1Scoreboard: MatchdayMvpScoreboardRow[],
  d2Scoreboard: MatchdayMvpScoreboardRow[],
) {
  const representativeRow = d1Scoreboard[0] ?? d2Scoreboard[0] ?? null;
  return {
    formCardSourceStatus: context.formCardSource?.effectStatus === "ready" ? "ready" as const : "missing_source" as const,
    formCardSourceLabel: context.formCardSource?.sourceLabel ?? null,
    mutatorSourceStatus: context.mutatorSource?.effectStatus === "ready" ? "ready" as const : "missing_source" as const,
    mutatorSourceLabel: context.mutatorSource?.sourceLabel ?? null,
    captainSourceStatus: representativeRow?.captainStatus ?? "missing_source",
    fatigueSourceStatus: representativeRow?.fatigueStatus ?? "missing_source",
    teamPpsSourceStatus: representativeRow?.teamPpsStatus ?? "missing_source",
  };
}

function buildMutatorSlotWarnings(
  scoreboard: MatchdayMvpScoreboardRow[],
  side: "d1" | "d2",
) {
  return scoreboard.flatMap((row) => {
    const warnings: string[] = [];
    if (!row.mutator1Label || row.mutator1Modifier == null) {
      warnings.push(`${side}:${row.teamId}:mutator1_missing`);
    }
    if (!row.mutator2Label || row.mutator2Modifier == null) {
      warnings.push(`${side}:${row.teamId}:mutator2_missing`);
    }
    return warnings;
  });
}

export async function runMatchdayMvpScoring(
  params: MatchdayMvpScoringParams,
  persistence: PersistenceService = createPersistenceService(),
): Promise<MatchdayMvpScoringResult> {
  if (params.source === "prisma") {
    throw new Error("Prisma/Supabase mode is read-only in this build.");
  }

  const dryRun = params.execute ? false : params.dryRun ?? true;
  if (!dryRun && params.confirmToken !== MATCHDAY_MVP_SCORING_CONFIRM_TOKEN) {
    throw new Error("Matchday MVP scoring execute requires explicit confirm token.");
  }

  const save = resolveStrictLocalSave(persistence, params.saveId);
  const seasonId = params.seasonId?.trim() || save.gameState.season.id;
  if (seasonId !== save.gameState.season.id) {
    throw new Error(`Requested season ${seasonId} is not available in save ${save.saveId}.`);
  }

  const targetMatchdayId = params.matchdayId?.trim() || save.gameState.season.matchdayIds[0] || save.gameState.matchdayState.matchdayId;
  if (!save.gameState.season.matchdayIds.includes(targetMatchdayId)) {
    throw new Error(`Requested matchday ${targetMatchdayId} is not available in save ${save.saveId}.`);
  }

  const scope = {
    saveId: save.saveId,
    seasonId,
    matchdayId: targetMatchdayId,
  };

  const rosterWarnings: string[] = [];
  const lineupTeams: MatchdayMvpLineupTeam[] = [];
  let nextGameState = structuredClone(save.gameState);
  const autoLineupTeamIds = new Set<string>();

  for (const team of [...save.gameState.teams].sort((left, right) => left.teamId.localeCompare(right.teamId))) {
    const contextResult = loadLocalLegacyLineupContextFromGameState(nextGameState, {
      saveId: scope.saveId,
      seasonId: scope.seasonId,
      matchdayId: scope.matchdayId,
      teamId: team.teamId,
    });
    const controlMode =
      nextGameState.seasonState.teamControlSettings?.[team.teamId]?.controlMode ??
      (team.humanControlled ? "manual" : "ai");
    const target = resolveTargetRoster(team, nextGameState);
    const teamRosterCount = nextGameState.rosters.filter((entry) => entry.teamId === team.teamId).length;

    if (!contextResult.ok) {
      lineupTeams.push({
        teamId: team.teamId,
        teamCode: team.shortCode,
        teamName: team.name,
        controlMode,
        readinessBefore: "unknown",
        rosterCount: teamRosterCount,
        requiredPlayers: 0,
        targetRosterSize: target.targetRosterSize,
        targetSource: target.targetSource,
        status: "blocked_missing_matchday_contract",
        autoGenerated: false,
        warnings: contextResult.warnings,
        blockingReasons: contextResult.errors,
      });
      continue;
    }

    const readiness = buildLegacyMatchdayReadiness(contextResult.context);
    if (target.targetRosterSize == null) {
      rosterWarnings.push(`${team.name}: target_roster_size_missing`);
    } else if (teamRosterCount < target.targetRosterSize) {
      rosterWarnings.push(`${team.name}: below_planning_target (${teamRosterCount}/${target.targetRosterSize})`);
    }

    if (readiness.matchdayReady && contextResult.context.existingDraft) {
      lineupTeams.push({
        teamId: team.teamId,
        teamCode: team.shortCode,
        teamName: team.name,
        controlMode,
        readinessBefore: readiness.readinessStatus,
        rosterCount: readiness.activePlayersCount,
        requiredPlayers: readiness.requiredTotalUniquePlayers,
        targetRosterSize: target.targetRosterSize,
        targetSource: target.targetSource,
        status: "existing_lineup",
        autoGenerated: false,
        warnings: [],
        blockingReasons: [],
      });
      continue;
    }

    if (readiness.activePlayersCount < MATCHDAY_MINIMUM_PLAYERS) {
      lineupTeams.push({
        teamId: team.teamId,
        teamCode: team.shortCode,
        teamName: team.name,
        controlMode,
        readinessBefore: readiness.readinessStatus,
        rosterCount: readiness.activePlayersCount,
        requiredPlayers: readiness.requiredTotalUniquePlayers,
        targetRosterSize: target.targetRosterSize,
        targetSource: target.targetSource,
        status: "blocked_underfilled_roster",
        autoGenerated: false,
        warnings: [
          ...readiness.validationWarnings,
          `Minimum ${MATCHDAY_MINIMUM_PLAYERS} active players required, current roster has ${readiness.activePlayersCount}.`,
        ],
        blockingReasons: readiness.reasonCodes,
      });
      continue;
    }

    const preview = buildAiLegacyLineupPreview(contextResult.context, "sqlite");
    if (preview.status === "blocked" || preview.status === "missing_scores") {
      lineupTeams.push({
        teamId: team.teamId,
        teamCode: team.shortCode,
        teamName: team.name,
        controlMode,
        readinessBefore: readiness.readinessStatus,
        rosterCount: readiness.activePlayersCount,
        requiredPlayers: readiness.requiredTotalUniquePlayers,
        targetRosterSize: target.targetRosterSize,
        targetSource: target.targetSource,
        status: preview.status === "missing_scores" ? "blocked_missing_scores" : "blocked_invalid_auto_lineup",
        autoGenerated: false,
        warnings: preview.warnings,
        blockingReasons: preview.warnings,
      });
      continue;
    }

    const validation = validateLegacyLineupContext(
      {
        ...contextResult.context,
        entries: preview.entries,
        disciplineSidePlayerCounts: buildDisciplineSidePlayerCounts(contextResult.context),
        disciplineSideCaptainCounts: contextResult.context.disciplineSideCaptainCounts,
      },
      {
        enforceCompleteness: readiness.activePlayersCount >= readiness.requiredTotalUniquePlayers && preview.status === "ready",
      },
    );

    if (!validation.isValid) {
      lineupTeams.push({
        teamId: team.teamId,
        teamCode: team.shortCode,
        teamName: team.name,
        controlMode,
        readinessBefore: readiness.readinessStatus,
        rosterCount: readiness.activePlayersCount,
        requiredPlayers: readiness.requiredTotalUniquePlayers,
        targetRosterSize: target.targetRosterSize,
        targetSource: target.targetSource,
        status: "blocked_invalid_auto_lineup",
        autoGenerated: false,
        warnings: validation.warnings,
        blockingReasons: validation.errors,
      });
      continue;
    }

    nextGameState = upsertDraftInGameState(
      nextGameState,
      {
        saveId: scope.saveId,
        seasonId: scope.seasonId,
        matchdayId: scope.matchdayId,
        teamId: team.teamId,
      },
      preview.entries,
    );
    autoLineupTeamIds.add(team.teamId);

    lineupTeams.push({
      teamId: team.teamId,
      teamCode: team.shortCode,
      teamName: team.name,
      controlMode,
      readinessBefore: readiness.readinessStatus,
      rosterCount: readiness.activePlayersCount,
      requiredPlayers: readiness.requiredTotalUniquePlayers,
      targetRosterSize: target.targetRosterSize,
      targetSource: target.targetSource,
      status: "auto_lineup_source",
      autoGenerated: true,
      warnings: Array.from(new Set(["auto_lineup_source", ...preview.warnings, ...validation.warnings])),
      blockingReasons: [],
    });
  }

  const blockedTeams = lineupTeams.filter((team) => team.blockingReasons.length > 0);
  const hypotheticalContextResults = buildContextsFromGameState(nextGameState, scope);
  const contextErrors = hypotheticalContextResults.flatMap((result) => (result.ok ? [] : result.errors));
  const hypotheticalContexts = hypotheticalContextResults.flatMap((result) => (result.ok ? [result.context] : []));

  if (hypotheticalContexts.length === 0) {
    return {
      source: "sqlite",
      dryRun,
      executed: !dryRun,
      status: "blocked",
      scope,
      targetMatchday: {
        matchdayId: scope.matchdayId,
        label: `Spieltag 1`,
        d1DisciplineId: null,
        d1DisciplineName: null,
        d2DisciplineId: null,
        d2DisciplineName: null,
      },
      rosterGate: buildRosterGate(lineupTeams, rosterWarnings),
      lineupSummary: {
        totalTeams: lineupTeams.length,
        existingLineups: 0,
        autoGeneratedLineups: autoLineupTeamIds.size,
        blockedTeams: blockedTeams.length,
      },
      resolveSources: {
        formCardSourceStatus: "missing_source",
        formCardSourceLabel: null,
        mutatorSourceStatus: "missing_source",
        mutatorSourceLabel: null,
        captainSourceStatus: "missing_source",
        fatigueSourceStatus: "missing_source",
        teamPpsSourceStatus: "missing_source",
      },
      lineupTeams,
      resolveStatus: "blocked",
      mutatorMode: "mvp_forced_mutators",
      d1Scoreboard: [],
      d2Scoreboard: [],
      d1TopPlayers: [],
      d2TopPlayers: [],
      ppWinners: [],
      totalTeamsScored: 0,
      resultApply: { applied: false, matchdayResultId: null, replacedExisting: false },
      standingsApply: { applied: false, auditLogId: null },
      warnings: [],
      blockingReasons: contextErrors.length > 0 ? contextErrors : ["no_matchday_contexts_loaded"],
    };
  }

  const firstContext = hypotheticalContexts[0]!;
  const targetMatchday = {
    matchdayId: firstContext.matchday.id,
    label: firstContext.matchday.label,
    d1DisciplineId: firstContext.contextMeta.d1DisciplineId,
    d1DisciplineName: firstContext.matchdayContract?.discipline1?.displayName ?? null,
    d2DisciplineId: firstContext.contextMeta.d2DisciplineId,
    d2DisciplineName: firstContext.matchdayContract?.discipline2?.displayName ?? null,
  };

  const prepared = await prepareLegacyMatchdayResultApply(
      {
        saveId: scope.saveId,
        seasonId: scope.seasonId,
        matchdayId: scope.matchdayId,
        source: "sqlite",
        forceReplace: Boolean(params.forceReplace),
        allowIncompleteOverride: true,
      },
    {
      persistence,
      localLoader: (loaderParams) =>
        loadLocalLegacyLineupContextFromGameState(nextGameState, loaderParams),
      resolveOptions: {
        modifierMode: "mvp_forced_mutators",
        captainMode: "missing_source",
      },
      sourceVersion: "matchday-mvp-resolve-v2",
    },
  );

  const d1Scoreboard: MatchdayMvpScoreboardRow[] =
    prepared.preview.disciplinePreviews
      .filter((preview) => preview.disciplineSide === "d1")
      .flatMap((preview) =>
        preview.teamResults.map((teamResult) => buildScoreboardRow(teamResult, autoLineupTeamIds)),
      );
  const d2Scoreboard: MatchdayMvpScoreboardRow[] =
    prepared.preview.disciplinePreviews
      .filter((preview) => preview.disciplineSide === "d2")
      .flatMap((preview) =>
        preview.teamResults.map((teamResult) => buildScoreboardRow(teamResult, autoLineupTeamIds)),
      );
  const d1TopPlayers =
    prepared.preview.disciplinePreviews
      .filter((preview) => preview.disciplineSide === "d1")
      .flatMap((preview) => preview.topPlayers.slice(0, 10).map((player) => buildTopPlayerRow(preview, player)));
  const d2TopPlayers =
    prepared.preview.disciplinePreviews
      .filter((preview) => preview.disciplineSide === "d2")
      .flatMap((preview) => preview.topPlayers.slice(0, 10).map((player) => buildTopPlayerRow(preview, player)));
  const ppWinners = [...d1TopPlayers, ...d2TopPlayers]
    .filter((player) => (player.mutatorPpsBonus ?? 0) > 0 || (player.pointsAwarded ?? 0) > 0)
    .sort((left, right) => (right.mutatorPpsBonus ?? 0) - (left.mutatorPpsBonus ?? 0) || (right.pointsAwarded ?? 0) - (left.pointsAwarded ?? 0))
    .slice(0, 10);
  const resolveSources = buildResolveSources(firstContext, d1Scoreboard, d2Scoreboard);
  const mutatorSlotWarnings = [
    ...buildMutatorSlotWarnings(d1Scoreboard, "d1"),
    ...buildMutatorSlotWarnings(d2Scoreboard, "d2"),
  ];

  const duplicateResultBlockers = prepared.blockingReasons.filter((reason) => reason.includes("already exists"));
  const blockingReasons = Array.from(
    new Set([
      ...blockedTeams.flatMap((team) => team.blockingReasons),
      ...prepared.blockingReasons.filter((reason) => !duplicateResultBlockers.includes(reason)),
      ...contextErrors,
      ...mutatorSlotWarnings,
    ]),
  );
  const warnings = Array.from(
    new Set([
      ...rosterWarnings,
      ...lineupTeams.flatMap((team) => team.warnings),
      ...prepared.preview.warnings,
      ...(duplicateResultBlockers.length > 0 ? duplicateResultBlockers : []),
    ]),
  );

  if (blockingReasons.length > 0 || dryRun) {
    const dryRunStatus =
      blockingReasons.length > 0
        ? "blocked"
        : duplicateResultBlockers.length > 0
          ? "warning"
          : warnings.length > 0
            ? "warning"
            : "ready";
    return {
      source: "sqlite",
      dryRun,
      executed: !dryRun,
      status: dryRun ? dryRunStatus : "blocked",
      scope,
      targetMatchday,
      rosterGate: buildRosterGate(lineupTeams, rosterWarnings),
      lineupSummary: {
        totalTeams: lineupTeams.length,
        existingLineups: lineupTeams.filter((team) => team.status === "existing_lineup").length,
        autoGeneratedLineups: autoLineupTeamIds.size,
        blockedTeams: blockedTeams.length,
      },
      resolveSources,
      lineupTeams,
      resolveStatus: prepared.preview.status,
      mutatorMode: "mvp_forced_mutators",
      d1Scoreboard,
      d2Scoreboard,
      d1TopPlayers,
      d2TopPlayers,
      ppWinners,
      totalTeamsScored: prepared.preview.teamResults.length,
      resultApply: {
        applied: false,
        matchdayResultId: prepared.existingResultId ?? prepared.writePayload.matchdayResultPayload.id,
        replacedExisting: Boolean(prepared.existingResultId),
      },
      standingsApply: {
        applied: false,
        auditLogId: null,
      },
      warnings,
      blockingReasons,
    };
  }

  persistence.saveSingleplayerState(scope.saveId, refreshTeamObjectiveState(nextGameState));

  const resultApplyService = new LegacyMatchdayResultApplyService(undefined, undefined, persistence);
  const resultApply = await resultApplyService.applyLegacyMatchdayResult({
    saveId: scope.saveId,
    seasonId: scope.seasonId,
    matchdayId: scope.matchdayId,
    source: "sqlite",
    execute: true,
    dryRun: false,
    confirm: RESULT_APPLY_CONFIRM_TOKEN,
    forceReplace: Boolean(params.forceReplace),
    allowIncompleteOverride: true,
    resolveOptions: {
      modifierMode: "mvp_forced_mutators",
      captainMode: "missing_source",
    },
  });

  if (!resultApply.ok || !resultApply.applied) {
    return {
      source: "sqlite",
      dryRun: false,
      executed: true,
      status: "blocked",
      scope,
      targetMatchday,
      rosterGate: buildRosterGate(lineupTeams, rosterWarnings),
      lineupSummary: {
        totalTeams: lineupTeams.length,
        existingLineups: lineupTeams.filter((team) => team.status === "existing_lineup").length,
        autoGeneratedLineups: autoLineupTeamIds.size,
        blockedTeams: blockedTeams.length,
      },
      resolveSources,
      lineupTeams,
      resolveStatus: prepared.preview.status,
      mutatorMode: "mvp_forced_mutators",
      d1Scoreboard,
      d2Scoreboard,
      d1TopPlayers,
      d2TopPlayers,
      ppWinners,
      totalTeamsScored: prepared.preview.teamResults.length,
      resultApply: {
        applied: false,
        matchdayResultId: null,
        replacedExisting: false,
      },
      standingsApply: {
        applied: false,
        auditLogId: null,
      },
      warnings,
      blockingReasons: [
        ...(!resultApply.ok && resultApply.error ? [resultApply.error] : []),
        ...(resultApply.blockingReasons ?? []),
      ],
    };
  }

  const standingsApply = await executeStandingsApply(
    {
      saveId: scope.saveId,
      seasonId: scope.seasonId,
      matchdayId: scope.matchdayId,
      source: "sqlite",
      confirm: STANDINGS_APPLY_CONFIRM_TOKEN,
      forceReplace: Boolean(params.forceReplace),
    },
    persistence,
  );

  if (!standingsApply.applied) {
    return {
      source: "sqlite",
      dryRun: false,
      executed: true,
      status: "warning",
      scope,
      targetMatchday,
      rosterGate: buildRosterGate(lineupTeams, rosterWarnings),
      lineupSummary: {
        totalTeams: lineupTeams.length,
        existingLineups: lineupTeams.filter((team) => team.status === "existing_lineup").length,
        autoGeneratedLineups: autoLineupTeamIds.size,
        blockedTeams: blockedTeams.length,
      },
      resolveSources,
      lineupTeams,
      resolveStatus: prepared.preview.status,
      mutatorMode: "mvp_forced_mutators",
      d1Scoreboard,
      d2Scoreboard,
      d1TopPlayers,
      d2TopPlayers,
      ppWinners,
      totalTeamsScored: prepared.preview.teamResults.length,
      resultApply: {
        applied: true,
        matchdayResultId: resultApply.matchdayResultId,
        replacedExisting: resultApply.replacedExisting,
      },
      standingsApply: {
        applied: false,
        auditLogId: standingsApply.auditLogId,
      },
      warnings: [...warnings, ...standingsApply.warnings],
      blockingReasons: standingsApply.blockingReasons,
    };
  }

  return {
    source: "sqlite",
    dryRun: false,
    executed: true,
    status: "applied",
    scope,
    targetMatchday,
    rosterGate: buildRosterGate(lineupTeams, rosterWarnings),
    lineupSummary: {
      totalTeams: lineupTeams.length,
      existingLineups: lineupTeams.filter((team) => team.status === "existing_lineup").length,
      autoGeneratedLineups: autoLineupTeamIds.size,
      blockedTeams: blockedTeams.length,
    },
    resolveSources,
    lineupTeams,
    resolveStatus: prepared.preview.status,
    mutatorMode: "mvp_forced_mutators",
    d1Scoreboard,
    d2Scoreboard,
    d1TopPlayers,
    d2TopPlayers,
    ppWinners,
    totalTeamsScored: prepared.preview.teamResults.length,
    resultApply: {
      applied: true,
      matchdayResultId: resultApply.matchdayResultId,
      replacedExisting: resultApply.replacedExisting,
    },
    standingsApply: {
      applied: true,
      auditLogId: standingsApply.auditLogId,
    },
    warnings: [...warnings, ...standingsApply.warnings],
    blockingReasons: [],
  };
}
