import { beforeEach, describe, expect, it, vi } from "vitest";

const runMatchdayMvpScoring = vi.fn();

vi.mock("@/lib/season/matchday-mvp-scoring-service", () => ({
  MATCHDAY_MVP_SCORING_CONFIRM_TOKEN: "RUN_MATCHDAY_MVP_SCORING",
  runMatchdayMvpScoring,
}));

describe("matchday MVP score api", () => {
  beforeEach(() => {
    runMatchdayMvpScoring.mockReset();
  });

  it("validates required parameters", async () => {
    const { POST } = await import("@/app/api/season/matchday-mvp-score/route");
    const response = await POST(
      new Request("http://localhost/api/season/matchday-mvp-score", {
        method: "POST",
        body: JSON.stringify({ saveId: "save-only" }),
      }),
    );

    expect(response.status).toBe(400);
  });

  it("blocks prisma mode", async () => {
    const { POST } = await import("@/app/api/season/matchday-mvp-score/route");
    const response = await POST(
      new Request("http://localhost/api/season/matchday-mvp-score", {
        method: "POST",
        body: JSON.stringify({
          saveId: "save-1",
          seasonId: "season-1",
          source: "prisma",
        }),
      }),
    );

    expect(response.status).toBe(409);
  });

  it("returns the scoring summary on success", async () => {
    runMatchdayMvpScoring.mockResolvedValue({
      source: "sqlite",
      dryRun: true,
      executed: false,
      status: "ready",
      scope: { saveId: "save-1", seasonId: "season-1", matchdayId: "matchday-1" },
      targetMatchday: {
        matchdayId: "matchday-1",
        label: "Spieltag 1",
        d1DisciplineId: "mini-dm",
        d1DisciplineName: "Mini DM",
        d2DisciplineId: "fechten",
        d2DisciplineName: "Fechten",
      },
      rosterGate: { teamsBelowMinimum: 0, teamsBelowTarget: 0, teamsMissingTarget: 0, warnings: [] },
      lineupSummary: { totalTeams: 32, existingLineups: 0, autoGeneratedLineups: 32, blockedTeams: 0 },
      lineupTeams: [],
      resolveStatus: "ready",
      mutatorMode: "legacy_selected_traits",
      d1Scoreboard: [],
      d2Scoreboard: [],
      d1TopPlayers: [],
      d2TopPlayers: [],
      ppWinners: [],
      totalTeamsScored: 32,
      resultApply: { applied: false, matchdayResultId: "result-1", replacedExisting: false },
      standingsApply: { applied: false, auditLogId: null },
      warnings: [],
      blockingReasons: [],
    });

    const { POST } = await import("@/app/api/season/matchday-mvp-score/route");
    const response = await POST(
      new Request("http://localhost/api/season/matchday-mvp-score", {
        method: "POST",
        body: JSON.stringify({
          saveId: "save-1",
          seasonId: "season-1",
          matchdayId: "matchday-1",
        }),
      }),
    );

    const body = await response.json();
    expect(response.status).toBe(200);
    expect(body.success).toBe(true);
    expect(body.summary.totalTeamsScored).toBe(32);
  });
});
