import type { GameState, Team, TeamIdentity, TeamStrategyBias, TeamStrategyLevel, TeamStrategyProfile } from "@/lib/data/olyDataTypes";
import { deriveTeamIdentityAxisBias } from "@/lib/foundation/team-identity-settings";

const neutralBias = (): TeamStrategyBias => ({
  cashPriority: 5,
  valuePriority: 5,
  starPriority: 5,
  riskTolerance: 5,
  wageSensitivity: 5,
  sellForProfitAggression: 5,
  shortContractPreference: 5,
  longContractPreference: 5,
  loyaltyBias: 5,
  harmonyStrictness: 5,
  rosterDepthPreference: 5,
  eliteSmallRosterPreference: 5,
});

type StrategySeed = Omit<TeamStrategyProfile, "teamId">;

function createProfile(seed: Partial<StrategySeed> & Pick<StrategySeed, "strategySummary">): StrategySeed {
  return {
    strategyVersion: seed.strategyVersion ?? "v1-local",
    strategySummary: seed.strategySummary,
    buyStyle: seed.buyStyle ?? "Balanced scouting around team identity, role fit and manageable contracts.",
    sellStyle: seed.sellStyle ?? "Sells when role fit and value drift apart, but does not force churn without reason.",
    contractStyle: seed.contractStyle ?? "Prefers stable local contracts without forcing extremes.",
    rosterStyle: seed.rosterStyle ?? "Keeps a balanced roster around the team identity and current matchday needs.",
    fantasyTheme: seed.fantasyTheme ?? null,
    loreTheme: seed.loreTheme ?? null,
    preferredArchetypes: seed.preferredArchetypes ?? [],
    secondaryArchetypes: seed.secondaryArchetypes ?? [],
    avoidedArchetypes: seed.avoidedArchetypes ?? [],
    dislikedArchetypes: seed.dislikedArchetypes ?? [],
    preferredRaces: seed.preferredRaces ?? [],
    avoidedRaces: seed.avoidedRaces ?? [],
    dislikedRaces: seed.dislikedRaces ?? [],
    preferredClasses: seed.preferredClasses ?? [],
    avoidedClasses: seed.avoidedClasses ?? [],
    dislikedClasses: seed.dislikedClasses ?? [],
    preferredTraits: seed.preferredTraits ?? [],
    dislikedTraits: seed.dislikedTraits ?? [],
    rosterMinTarget: seed.rosterMinTarget ?? null,
    rosterOptTarget: seed.rosterOptTarget ?? null,
    prefersDepth: seed.prefersDepth,
    prefersStars: seed.prefersStars,
    prefersAllrounders: seed.prefersAllrounders,
    prefersSpecialists: seed.prefersSpecialists,
    shortContractsBias: seed.shortContractsBias,
    longContractsBias: seed.longContractsBias,
    spendAggression: seed.spendAggression,
    saveDiscipline: seed.saveDiscipline,
    overpayTolerance: seed.overpayTolerance,
    sellAggression: seed.sellAggression,
    profitSellBias: seed.profitSellBias,
    loyaltyPreference: seed.loyaltyPreference,
    riskToleranceLevel: seed.riskToleranceLevel,
    emergencyBuyBias: seed.emergencyBuyBias,
    powBias: seed.powBias ?? null,
    speBias: seed.speBias ?? null,
    menBias: seed.menBias ?? null,
    socBias: seed.socBias ?? null,
    lineupStyleNote: seed.lineupStyleNote ?? null,
    transferStyleNote: seed.transferStyleNote ?? null,
    sellStyleNote: seed.sellStyleNote ?? null,
    hardNoGos: seed.hardNoGos ?? [],
    lockedNoGos: seed.lockedNoGos ?? [],
    strategyWarnings: seed.strategyWarnings ?? [],
    notes: seed.notes ?? null,
    bias: {
      ...neutralBias(),
      ...(seed.bias ?? {}),
    },
  };
}

function clampBias(value: number) {
  return Math.max(1, Math.min(10, Math.round(value)));
}

function levelFromBias(value: number | null | undefined): TeamStrategyLevel {
  const next = typeof value === "number" && Number.isFinite(value) ? value : 5;
  if (next >= 8) return "high";
  if (next <= 3) return "low";
  return "medium";
}

function levelFromComposite(...values: Array<number | null | undefined>): TeamStrategyLevel {
  const valid = values.filter((value): value is number => typeof value === "number" && Number.isFinite(value));
  if (valid.length === 0) {
    return "medium";
  }

  const average = valid.reduce((sum, value) => sum + value, 0) / valid.length;
  return levelFromBias(average);
}

function fallbackTheme(summary: string) {
  const [first] = summary.split(".");
  return first?.trim() || summary.trim();
}

function deriveSecondaryArchetypes(profile: TeamStrategyProfile) {
  if (profile.secondaryArchetypes && profile.secondaryArchetypes.length > 0) {
    return profile.secondaryArchetypes;
  }

  return profile.preferredArchetypes.slice(1, 4);
}

function normalizeStrategyProfile(team: Team, identity: TeamIdentity | null | undefined, profile: TeamStrategyProfile): TeamStrategyProfile {
  const derivedAxisBias = deriveTeamIdentityAxisBias(identity);
  const normalizedBias = {
    ...neutralBias(),
    ...(profile.bias ?? {}),
  };

  return {
    ...profile,
    teamId: team.teamId,
    teamCode: profile.teamCode ?? team.shortCode,
    teamName: profile.teamName ?? team.name,
    strategyVersion: profile.strategyVersion ?? "v1-local",
    fantasyTheme: profile.fantasyTheme ?? fallbackTheme(profile.strategySummary),
    loreTheme: profile.loreTheme ?? profile.strategySummary,
    avoidedArchetypes:
      profile.avoidedArchetypes && profile.avoidedArchetypes.length > 0
        ? profile.avoidedArchetypes
        : profile.dislikedArchetypes ?? [],
    secondaryArchetypes: deriveSecondaryArchetypes(profile),
    dislikedArchetypes: profile.dislikedArchetypes ?? profile.avoidedArchetypes ?? [],
    avoidedRaces:
      profile.avoidedRaces && profile.avoidedRaces.length > 0 ? profile.avoidedRaces : profile.dislikedRaces ?? [],
    dislikedRaces: profile.dislikedRaces ?? profile.avoidedRaces ?? [],
    avoidedClasses:
      profile.avoidedClasses && profile.avoidedClasses.length > 0
        ? profile.avoidedClasses
        : profile.dislikedClasses ?? [],
    dislikedClasses: profile.dislikedClasses ?? profile.avoidedClasses ?? [],
    preferredTraits: profile.preferredTraits ?? [],
    dislikedTraits: profile.dislikedTraits ?? [],
    rosterMinTarget: profile.rosterMinTarget ?? identity?.playerMin ?? null,
    rosterOptTarget: profile.rosterOptTarget ?? identity?.playerOpt ?? null,
    prefersDepth: profile.prefersDepth ?? levelFromBias(normalizedBias.rosterDepthPreference),
    prefersStars: profile.prefersStars ?? levelFromBias(normalizedBias.starPriority),
    prefersAllrounders:
      profile.prefersAllrounders ??
      levelFromComposite(normalizedBias.rosterDepthPreference, 11 - normalizedBias.eliteSmallRosterPreference),
    prefersSpecialists:
      profile.prefersSpecialists ??
      levelFromComposite(normalizedBias.starPriority, normalizedBias.eliteSmallRosterPreference),
    shortContractsBias: profile.shortContractsBias ?? levelFromBias(normalizedBias.shortContractPreference),
    longContractsBias: profile.longContractsBias ?? levelFromBias(normalizedBias.longContractPreference),
    spendAggression: profile.spendAggression ?? levelFromComposite(normalizedBias.starPriority, normalizedBias.riskTolerance),
    saveDiscipline: profile.saveDiscipline ?? levelFromComposite(normalizedBias.cashPriority, normalizedBias.wageSensitivity),
    overpayTolerance: profile.overpayTolerance ?? levelFromComposite(normalizedBias.starPriority, normalizedBias.riskTolerance),
    sellAggression: profile.sellAggression ?? levelFromBias(normalizedBias.sellForProfitAggression),
    profitSellBias: profile.profitSellBias ?? levelFromBias(normalizedBias.sellForProfitAggression),
    loyaltyPreference: profile.loyaltyPreference ?? levelFromBias(normalizedBias.loyaltyBias),
    riskToleranceLevel: profile.riskToleranceLevel ?? levelFromBias(normalizedBias.riskTolerance),
    emergencyBuyBias:
      profile.emergencyBuyBias ??
      levelFromComposite(
        normalizedBias.rosterDepthPreference,
        normalizedBias.riskTolerance,
        profile.rosterMinTarget != null && profile.rosterOptTarget != null && profile.rosterMinTarget < profile.rosterOptTarget ? 7 : 5,
      ),
    powBias: derivedAxisBias?.pow ?? null,
    speBias: derivedAxisBias?.spe ?? null,
    menBias: derivedAxisBias?.men ?? null,
    socBias: derivedAxisBias?.soc ?? null,
    hardNoGos: profile.hardNoGos && profile.hardNoGos.length > 0 ? profile.hardNoGos : profile.lockedNoGos ?? [],
    lineupStyleNote: profile.lineupStyleNote ?? profile.rosterStyle,
    transferStyleNote: profile.transferStyleNote ?? profile.buyStyle,
    sellStyleNote: profile.sellStyleNote ?? profile.sellStyle,
    lockedNoGos: profile.lockedNoGos ?? profile.hardNoGos ?? [],
    strategyWarnings: profile.strategyWarnings ?? [],
    bias: {
      cashPriority: clampBias(normalizedBias.cashPriority),
      valuePriority: clampBias(normalizedBias.valuePriority),
      starPriority: clampBias(normalizedBias.starPriority),
      riskTolerance: clampBias(normalizedBias.riskTolerance),
      wageSensitivity: clampBias(normalizedBias.wageSensitivity),
      sellForProfitAggression: clampBias(normalizedBias.sellForProfitAggression),
      shortContractPreference: clampBias(normalizedBias.shortContractPreference),
      longContractPreference: clampBias(normalizedBias.longContractPreference),
      loyaltyBias: clampBias(normalizedBias.loyaltyBias),
      harmonyStrictness: clampBias(normalizedBias.harmonyStrictness),
      rosterDepthPreference: clampBias(normalizedBias.rosterDepthPreference),
      eliteSmallRosterPreference: clampBias(normalizedBias.eliteSmallRosterPreference),
    },
  };
}

const strategySeedsByTeamId: Record<string, StrategySeed> = {
  "C-C": createProfile({
    strategySummary: "Bank der Olympiade. Sucht Value, kuerzere Bindung und handelbare Kaderplaetze statt sentimentaler Langzeitwetten.",
    buyStyle: "Kauft unter Marktpreis, moeglichst flexibel, und priorisiert Spieler mit gutem Preis-Leistungs-Verhaeltnis.",
    sellStyle: "Verkauft schnell, wenn ein sauberer Profit oder ein besserer Reinvest moeglich ist.",
    contractStyle: "Kurz bis mittel, ungern teure Langzeitbindungen.",
    rosterStyle: "Schlanker 11-12er Kader mit klarer Handelsreserve.",
    preferredArchetypes: ["value hunter", "mercenary", "plug-and-play depth", "high liquidity veteran"],
    avoidedArchetypes: ["luxury bench", "long rehab project"],
    hardNoGos: ["dead salary", "long expensive bench contracts"],
    bias: {
      cashPriority: 10,
      valuePriority: 10,
      starPriority: 4,
      riskTolerance: 6,
      wageSensitivity: 9,
      sellForProfitAggression: 10,
      shortContractPreference: 9,
      longContractPreference: 2,
      loyaltyBias: 2,
      harmonyStrictness: 4,
      rosterDepthPreference: 6,
      eliteSmallRosterPreference: 8,
    },
  }),
  "W-W": createProfile({
    strategySummary: "Magier, Zauberwirker und Golems. Mental-Stars sind willkommen, rohe Brute-Force ohne Gehirn eher nicht.",
    buyStyle: "Sucht magische, intelligente und willensstarke Profile mit klarer Mental-Decke.",
    sellStyle: "Trennt sich eher von dumpfen Fehlfits als von Mental-Stars.",
    contractStyle: "Bindet echte Spell-Core-Spieler gern mittel bis lang.",
    rosterStyle: "Kleiner bis mittlerer Kern mit magischer Spezialisierung.",
    preferredArchetypes: ["mage", "wizard", "warlock", "golem", "mental star"],
    avoidedArchetypes: ["mindless bruiser", "pure brawler"],
    preferredRaces: ["construct", "spirit", "arcane"],
    preferredClasses: ["Mage", "Wizard", "Warlock", "Summoner"],
    hardNoGos: ["anti-magic locker-room anchor"],
    bias: {
      cashPriority: 4,
      valuePriority: 6,
      starPriority: 8,
      riskTolerance: 6,
      wageSensitivity: 5,
      sellForProfitAggression: 4,
      shortContractPreference: 3,
      longContractPreference: 8,
      loyaltyBias: 7,
      harmonyStrictness: 6,
      rosterDepthPreference: 4,
      eliteSmallRosterPreference: 7,
    },
  }),
  "T-T": createProfile({
    strategySummary: "Teacher/Leader-Kern mit bewusst schwacherem Umfeld. Ein oder zwei starke Leitfiguren tragen die Klasse.",
    buyStyle: "Investiert in starke Lehrer, Leader und Taktgeber, nicht in tiefe Luxusrotation.",
    sellStyle: "Depth ist verhandelbar, Mentor-Figuren nur gegen klare Verbesserung.",
    contractStyle: "Fuehrungsspieler lieber sicher binden, Schueler kurz halten.",
    rosterStyle: "Spitze oben, bewusst einfacher Unterbau.",
    preferredArchetypes: ["teacher", "leader", "mentor", "captain"],
    avoidedArchetypes: ["ego bench star", "expensive project depth"],
    preferredClasses: ["Teacher", "Leader", "Captain"],
    hardNoGos: ["locker-room mutineer"],
    bias: {
      cashPriority: 5,
      valuePriority: 5,
      starPriority: 7,
      riskTolerance: 4,
      wageSensitivity: 6,
      sellForProfitAggression: 4,
      shortContractPreference: 6,
      longContractPreference: 6,
      loyaltyBias: 8,
      harmonyStrictness: 8,
      rosterDepthPreference: 3,
      eliteSmallRosterPreference: 7,
    },
  }),
  "R-C": createProfile({
    strategySummary: "Royaler Status-Kader. Praesenz, Klasse und Hofetikette zaehlen neben der Leistung.",
    buyStyle: "Kauft Prestige-Spieler mit People-Fit und sauberer Aura.",
    sellStyle: "Verkauft, wenn Wuerde oder Stellung im Team leidet.",
    contractStyle: "Gern geordnete, wertschaetzende Langzeitbindungen fuer Kernrollen.",
    rosterStyle: "Edler Kern mit wenigen offensichtlichen Stilbrüchen.",
    preferredArchetypes: ["royal guard", "noble leader", "status veteran"],
    avoidedArchetypes: ["chaos gremlin", "street brawler"],
    hardNoGos: ["public embarrassment"],
    bias: {
      cashPriority: 4,
      valuePriority: 5,
      starPriority: 7,
      riskTolerance: 4,
      wageSensitivity: 4,
      sellForProfitAggression: 3,
      shortContractPreference: 3,
      longContractPreference: 7,
      loyaltyBias: 8,
      harmonyStrictness: 8,
      rosterDepthPreference: 5,
      eliteSmallRosterPreference: 6,
    },
  }),
  "R-R": createProfile({
    strategySummary: "Aqua-, Natur- und Sirenen-Vibe. Organischer Fit und fluide Rollen gehen vor brachialen Fremdkoerpern.",
    buyStyle: "Sucht fluide, natuerliche und wassernahe Profile mit weicher Teamchemie.",
    sellStyle: "Trennt sich von trockenen Fehlfits ohne organischen Flow.",
    contractStyle: "Mittel bis lang fuer organisch passende Kernspieler.",
    rosterStyle: "Ausbalancierter, harmonischer Kern statt Maximalchaos.",
    preferredArchetypes: ["siren", "river scout", "nature dancer", "aqua mage"],
    avoidedArchetypes: ["heavy metal bruiser", "rigid crusader"],
    preferredRaces: ["aquatic", "nature", "spirit"],
    hardNoGos: ["hard anti-nature vibe"],
    bias: {
      cashPriority: 4,
      valuePriority: 6,
      starPriority: 5,
      riskTolerance: 4,
      wageSensitivity: 5,
      sellForProfitAggression: 4,
      shortContractPreference: 4,
      longContractPreference: 7,
      loyaltyBias: 7,
      harmonyStrictness: 8,
      rosterDepthPreference: 6,
      eliteSmallRosterPreference: 4,
    },
  }),
  "M-S": createProfile({
    strategySummary: "Social- und Harmonie-Team mit dunkler Verfuehrung. Chemie ist Pflicht, offener Konflikt kostet zu viel.",
    buyStyle: "Sucht sozial starke, elegante und manipulative Fits mit sauberer Teamresonanz.",
    sellStyle: "Verkauft toxische Fremdkoerper frueh.",
    contractStyle: "Bindet harmonische Kernspieler laenger als rein effiziente Rentals.",
    rosterStyle: "Geschlossener Kern mit hohem Chemieanspruch.",
    preferredArchetypes: ["charmer", "temptress", "social controller"],
    avoidedArchetypes: ["antisocial brute"],
    hardNoGos: ["locker-room chaos source"],
    bias: {
      cashPriority: 4,
      valuePriority: 5,
      starPriority: 6,
      riskTolerance: 4,
      wageSensitivity: 5,
      sellForProfitAggression: 4,
      shortContractPreference: 4,
      longContractPreference: 7,
      loyaltyBias: 7,
      harmonyStrictness: 10,
      rosterDepthPreference: 5,
      eliteSmallRosterPreference: 5,
    },
  }),
  "C-S": createProfile({
    strategySummary: "Ehrenhafte, praezise und agile Nahkaempfer. Stil und Disziplin wiegen mehr als lautes Spektakel.",
    buyStyle: "Sucht praezise Blade-, Duelist- und agile Melee-Profile mit sauberem Stil.",
    sellStyle: "Verkauft rohe, unpraezise Fehlfits eher als elegante Kernspieler.",
    contractStyle: "Saubere mittlere Laufzeiten, wenn Stil und Disziplin stimmen.",
    rosterStyle: "Klarer Stil-Kern ohne unnötigen Wildwuchs.",
    preferredArchetypes: ["swordsman", "duelist", "precision fighter", "agile melee"],
    avoidedArchetypes: ["sloppy berserker"],
    hardNoGos: ["dishonorable butcher fit"],
    bias: {
      cashPriority: 5,
      valuePriority: 6,
      starPriority: 6,
      riskTolerance: 4,
      wageSensitivity: 5,
      sellForProfitAggression: 5,
      shortContractPreference: 4,
      longContractPreference: 6,
      loyaltyBias: 6,
      harmonyStrictness: 7,
      rosterDepthPreference: 5,
      eliteSmallRosterPreference: 6,
    },
  }),
  "A-A": createProfile({
    strategySummary: "Fallout-/Endzeit-Kader. Isoliert, skeptisch und ablehnend gegen fremde Vibes.",
    buyStyle: "Kauft nur harte Ueberlebensprofile mit Endzeit-Fit und mentaler Zaehigkeit.",
    sellStyle: "Verkauft offene Fehlfits ohne Shelter-Mentalitaet schnell.",
    contractStyle: "Kurze Probephasen, lange Deals nur fuer echte Survivors.",
    rosterStyle: "Zaeher Kern mit Misstrauen gegen Fremdkoerper.",
    preferredArchetypes: ["survivor", "wasteland bruiser", "scavenger", "grim veteran"],
    avoidedArchetypes: ["court darling", "soft celebrity"],
    hardNoGos: ["fragile diva", "utopian choir fit"],
    bias: {
      cashPriority: 6,
      valuePriority: 6,
      starPriority: 4,
      riskTolerance: 6,
      wageSensitivity: 7,
      sellForProfitAggression: 5,
      shortContractPreference: 7,
      longContractPreference: 3,
      loyaltyBias: 4,
      harmonyStrictness: 6,
      rosterDepthPreference: 7,
      eliteSmallRosterPreference: 4,
    },
  }),
  "N-N": createProfile({
    strategySummary: "Agile Ninja-/Assassin-Truppe. Tempo, Stealth und surgical strikes stehen ueber roher Masse.",
    buyStyle: "Kauft agile Assassins, Ninjas und flankierende Spezialisten.",
    sellStyle: "Verkauft laute, unbewegliche Bruiser zuerst.",
    contractStyle: "Mittel, mit Fokus auf mobile Kernspieler.",
    rosterStyle: "Leichter, agiler Kader mit klaren Rollen.",
    preferredArchetypes: ["ninja", "assassin", "shadow striker", "scout"],
    avoidedArchetypes: ["siege tank"],
    hardNoGos: ["slow telegraphed bruiser"],
    bias: {
      cashPriority: 5,
      valuePriority: 6,
      starPriority: 7,
      riskTolerance: 6,
      wageSensitivity: 5,
      sellForProfitAggression: 5,
      shortContractPreference: 5,
      longContractPreference: 5,
      loyaltyBias: 5,
      harmonyStrictness: 6,
      rosterDepthPreference: 4,
      eliteSmallRosterPreference: 8,
    },
  }),
  "T-G": createProfile({
    strategySummary: "Groesse und rohe Power im Zentrum. Klein, filigran und weich ist selten Prioritaet.",
    buyStyle: "Kauft Mass, Reach und brute force.",
    sellStyle: "Verkauft undersized Fehlfits eher als schwere Impact-Spieler.",
    contractStyle: "Bindet dominante Groessenprofile gern laenger.",
    rosterStyle: "Massiger Kern mit klarer Power-Identitaet.",
    preferredArchetypes: ["giant", "colossus", "tower bruiser", "power anchor"],
    avoidedArchetypes: ["tiny trickster"],
    hardNoGos: ["undersized finesse-only core piece"],
    bias: {
      cashPriority: 4,
      valuePriority: 5,
      starPriority: 8,
      riskTolerance: 5,
      wageSensitivity: 4,
      sellForProfitAggression: 3,
      shortContractPreference: 3,
      longContractPreference: 8,
      loyaltyBias: 7,
      harmonyStrictness: 5,
      rosterDepthPreference: 6,
      eliteSmallRosterPreference: 5,
    },
  }),
  "U-A": createProfile({
    strategySummary: "Agenten und Spec-Ops. Unsichtbare Vielseitigkeit und saubere Mission-Fits gehen vor Glanz.",
    buyStyle: "Sucht flexible covert operators mit ordentlicher Allround-Basis.",
    sellStyle: "Verkauft auffaellige Egos und laute Fehlfits.",
    contractStyle: "Mittel, mit Raum fuer taktische Neuausrichtung.",
    rosterStyle: "Sauberer mission-ready Kader ohne Ballast.",
    preferredArchetypes: ["agent", "operative", "saboteur", "infiltrator"],
    avoidedArchetypes: ["showboat superstar"],
    hardNoGos: ["cannot-follow-orders profile"],
    bias: {
      cashPriority: 5,
      valuePriority: 7,
      starPriority: 5,
      riskTolerance: 5,
      wageSensitivity: 6,
      sellForProfitAggression: 5,
      shortContractPreference: 5,
      longContractPreference: 5,
      loyaltyBias: 5,
      harmonyStrictness: 8,
      rosterDepthPreference: 6,
      eliteSmallRosterPreference: 6,
    },
  }),
  "D-L": createProfile({
    strategySummary: "Duestere Human-only Fraktion. Nicht-Humans werden stark gemieden, selbst bei Talentvorteilen.",
    buyStyle: "Kauft bevorzugt harte Human-Soldaten und disziplinierte Frontkaempfer.",
    sellStyle: "Nicht-Human-Fits und weich wirkende Profile werden sehr schnell abgestossen.",
    contractStyle: "Bindet loyal erscheinende Human-Kernspieler gerne laenger.",
    rosterStyle: "Enger, ideologisch enger Kern statt offener Vielfalt.",
    preferredArchetypes: ["human legionnaire", "discipline brute", "dark officer"],
    avoidedArchetypes: ["outsider mystic", "chaotic beast"],
    preferredRaces: ["human"],
    avoidedRaces: ["elf", "orc", "beast", "demon", "undead", "construct", "aquatic", "spirit"],
    hardNoGos: ["non-human core signing"],
    notes: "Faction bias modelliert als in-universe Stilregel, nicht als positive Wertung.",
    bias: {
      cashPriority: 5,
      valuePriority: 4,
      starPriority: 6,
      riskTolerance: 3,
      wageSensitivity: 5,
      sellForProfitAggression: 4,
      shortContractPreference: 4,
      longContractPreference: 8,
      loyaltyBias: 9,
      harmonyStrictness: 9,
      rosterDepthPreference: 7,
      eliteSmallRosterPreference: 4,
    },
  }),
  "S-C": createProfile({
    strategySummary: "Brutale Kreuzritter. Blut, Kampf und fanatische Frontstaerke sind Kernidentitaet.",
    buyStyle: "Kauft kompromisslose Frontkaempfer, zealots und executioner-Typen.",
    sellStyle: "Verkauft weiche, friedfertige oder zu trickreiche Fehlfits.",
    contractStyle: "Mittlere bis lange Bindungen fuer kampftaugliche Kernspieler.",
    rosterStyle: "Harter, aggressiver Frontkern mit Wucht.",
    preferredArchetypes: ["crusader", "paladin bruiser", "executioner", "zealot"],
    avoidedArchetypes: ["pacifist support"],
    hardNoGos: ["cowardice under pressure"],
    bias: {
      cashPriority: 4,
      valuePriority: 5,
      starPriority: 7,
      riskTolerance: 7,
      wageSensitivity: 4,
      sellForProfitAggression: 4,
      shortContractPreference: 3,
      longContractPreference: 7,
      loyaltyBias: 8,
      harmonyStrictness: 7,
      rosterDepthPreference: 6,
      eliteSmallRosterPreference: 5,
    },
  }),
  "B-P": createProfile({
    strategySummary: "Kleine Elite mit vielseitigem Top-End. Lieber wenige starke Zweiweg-Spieler als breite Mittelklasse.",
    buyStyle: "Kauft vielseitige Alpha-Profile und scheut Overpay fuer echte Difference-Maker weniger.",
    sellStyle: "Depth ist verhandelbar, Elite nur fuer Monster-Deals.",
    contractStyle: "Gern laenger fuer Topkern, kurz fuer Randrollen.",
    rosterStyle: "Kleiner, teurer, vielseitiger Elitekader.",
    preferredArchetypes: ["elite allrounder", "two-way star", "alpha closer"],
    avoidedArchetypes: ["low ceiling depth only"],
    hardNoGos: ["roster bloat"],
    bias: {
      cashPriority: 3,
      valuePriority: 5,
      starPriority: 9,
      riskTolerance: 7,
      wageSensitivity: 3,
      sellForProfitAggression: 4,
      shortContractPreference: 3,
      longContractPreference: 7,
      loyaltyBias: 6,
      harmonyStrictness: 6,
      rosterDepthPreference: 2,
      eliteSmallRosterPreference: 10,
    },
  }),
  "B-B": createProfile({
    strategySummary: "Wilde Power-/Speed-Monster. Beasts, Animals und Daemonen mit Charger-Energie stehen im Zentrum.",
    buyStyle: "Kauft wilde Charger, Berserker, Hellhounds und andere explosive Beast-Fits.",
    sellStyle: "Verkauft zivile, zahme oder zu menschliche Fehlfits frueh.",
    contractStyle: "Kurz bis mittel, solange Aggression und Impact hoch bleiben.",
    rosterStyle: "Explosiver Power-Speed-Kader mit Monster-Vibe.",
    preferredArchetypes: ["charger", "berserker", "hellhound", "beast bruiser"],
    avoidedArchetypes: ["civil clerk", "soft support"],
    preferredRaces: ["beast", "animal", "demon"],
    avoidedRaces: ["human"],
    hardNoGos: ["timid low-impact fit"],
    bias: {
      cashPriority: 4,
      valuePriority: 5,
      starPriority: 8,
      riskTolerance: 8,
      wageSensitivity: 4,
      sellForProfitAggression: 5,
      shortContractPreference: 6,
      longContractPreference: 4,
      loyaltyBias: 4,
      harmonyStrictness: 4,
      rosterDepthPreference: 5,
      eliteSmallRosterPreference: 7,
    },
  }),
  "D-P": createProfile({
    strategySummary: "Dark-Fantasy mit Succubi/Incubi-Vibe. Daemonisch, agil und manipulativ statt stumpf.",
    buyStyle: "Kauft agile, dunkle Social-/Speed-Fits mit Verfuehrungs- oder Finisher-Potenzial.",
    sellStyle: "Verkauft plumpe Fehlfits ohne Eleganz oder Bedrohung.",
    contractStyle: "Mittlere Bindungen fuer stilistische Kernspieler.",
    rosterStyle: "Dunkler, agiler, manipulativer Kern.",
    preferredArchetypes: ["succubus", "incubus", "shadow temptress", "agile demon"],
    avoidedArchetypes: ["holy tank", "rigid machine"],
    preferredRaces: ["demon"],
    hardNoGos: ["sanctimonious anti-demon core fit"],
    bias: {
      cashPriority: 4,
      valuePriority: 5,
      starPriority: 7,
      riskTolerance: 6,
      wageSensitivity: 4,
      sellForProfitAggression: 5,
      shortContractPreference: 5,
      longContractPreference: 5,
      loyaltyBias: 5,
      harmonyStrictness: 7,
      rosterDepthPreference: 4,
      eliteSmallRosterPreference: 7,
    },
  }),
  "G-G": createProfile({
    strategySummary: "Engel, Paladine und rechtschaffene Ordnung. Sauberkeit und moralischer Stil zaehlen stark mit.",
    buyStyle: "Kauft geordnete, strahlende und pflichtbewusste Fits.",
    sellStyle: "Verkauft duestere oder chaotische Stilbrüche eher frueh.",
    contractStyle: "Bindet passende Ordnungsspieler gerne laenger.",
    rosterStyle: "Sauberer Kern mit hoher Stilkonstanz.",
    preferredArchetypes: ["angel", "paladin", "holy guard", "lawful captain"],
    avoidedArchetypes: ["chaos demon", "sadist"],
    hardNoGos: ["corrupt locker-room toxin"],
    bias: {
      cashPriority: 4,
      valuePriority: 5,
      starPriority: 7,
      riskTolerance: 3,
      wageSensitivity: 5,
      sellForProfitAggression: 3,
      shortContractPreference: 3,
      longContractPreference: 8,
      loyaltyBias: 8,
      harmonyStrictness: 9,
      rosterDepthPreference: 5,
      eliteSmallRosterPreference: 6,
    },
  }),
  "H-R": createProfile({
    strategySummary: "Daemons from hell. Brutal, stark, schnell und teils mental stark.",
    buyStyle: "Kauft infernale Impact-Spieler mit Druck in Power, Speed und dunkler Mentalitaet.",
    sellStyle: "Verkauft brave Fehlfits ohne Hollenprofil.",
    contractStyle: "Mittlere Laufzeiten mit Bereitschaft zum schnellen Umbau.",
    rosterStyle: "Aggressiver infernaler Kern mit hoher Druckfaehigkeit.",
    preferredArchetypes: ["demon bruiser", "hell sprinter", "infernal warlord"],
    avoidedArchetypes: ["holy caretaker"],
    preferredRaces: ["demon"],
    hardNoGos: ["saintly morale mascot"],
    bias: {
      cashPriority: 4,
      valuePriority: 5,
      starPriority: 8,
      riskTolerance: 7,
      wageSensitivity: 4,
      sellForProfitAggression: 5,
      shortContractPreference: 5,
      longContractPreference: 5,
      loyaltyBias: 4,
      harmonyStrictness: 5,
      rosterDepthPreference: 5,
      eliteSmallRosterPreference: 7,
    },
  }),
  "L-R": createProfile({
    strategySummary: "Untote, Vampire und Lichs mit dunkler Intelligenz. Strength plus sinister brainpower.",
    buyStyle: "Kauft intelligente Untote, dunkle Controller und starke Nachtprofile.",
    sellStyle: "Verkauft lebendige Fehlfits ohne Friedhofsresonanz.",
    contractStyle: "Lang genug fuer dunklen Kern, aber nicht blind sentimental.",
    rosterStyle: "Dunkler Kern mit Kraft und Intellekt.",
    preferredArchetypes: ["vampire lord", "lich", "undead bruiser", "night tactician"],
    avoidedArchetypes: ["sunlit zealot"],
    preferredRaces: ["undead", "vampire"],
    hardNoGos: ["holy anti-undead centerpiece"],
    bias: {
      cashPriority: 4,
      valuePriority: 5,
      starPriority: 7,
      riskTolerance: 5,
      wageSensitivity: 4,
      sellForProfitAggression: 4,
      shortContractPreference: 4,
      longContractPreference: 7,
      loyaltyBias: 7,
      harmonyStrictness: 7,
      rosterDepthPreference: 5,
      eliteSmallRosterPreference: 6,
    },
  }),
  "L-K": createProfile({
    strategySummary: "Agile Untoten-Variante mit Vampire-Lords, Ghouls und mobilen Nachtjaegern.",
    buyStyle: "Kauft schnelle dunkle Untote und mobile Night-Stalkers.",
    sellStyle: "Verkauft schwere, steife Fehlfits ohne Nachtmobilitaet.",
    contractStyle: "Mittel, mit Fokus auf flexiblen Nachtkern.",
    rosterStyle: "Agiler untoter Kern statt reiner Grabsteinmasse.",
    preferredArchetypes: ["vampire lord", "ghoul", "night runner", "agile undead"],
    avoidedArchetypes: ["holy wall", "slow relic tank"],
    preferredRaces: ["undead", "vampire"],
    hardNoGos: ["anti-night holy profile"],
    bias: {
      cashPriority: 4,
      valuePriority: 6,
      starPriority: 7,
      riskTolerance: 6,
      wageSensitivity: 5,
      sellForProfitAggression: 5,
      shortContractPreference: 5,
      longContractPreference: 5,
      loyaltyBias: 6,
      harmonyStrictness: 6,
      rosterDepthPreference: 4,
      eliteSmallRosterPreference: 7,
    },
  }),
  "N-W": createProfile({
    strategySummary: "Naturgewalten, Waldwesen und Balance der Welt. Organischer Fit und Gleichgewicht zaehlen stark.",
    buyStyle: "Kauft Natur-, Wald- und Gleichgewichtsprofile mit organischer Chemie.",
    sellStyle: "Verkauft industrielle, toxische oder extrem unnatuerliche Fehlfits eher frueh.",
    contractStyle: "Passende Kernspieler eher laenger halten.",
    rosterStyle: "Balance statt reines Star-Hunting.",
    preferredArchetypes: ["druid", "forest guardian", "beast ally", "nature spirit"],
    avoidedArchetypes: ["factory construct", "polluted berserker"],
    preferredRaces: ["nature", "beast", "spirit"],
    hardNoGos: ["anti-nature destroyer"],
    bias: {
      cashPriority: 4,
      valuePriority: 6,
      starPriority: 5,
      riskTolerance: 4,
      wageSensitivity: 5,
      sellForProfitAggression: 4,
      shortContractPreference: 4,
      longContractPreference: 7,
      loyaltyBias: 8,
      harmonyStrictness: 8,
      rosterDepthPreference: 6,
      eliteSmallRosterPreference: 4,
    },
  }),
  "P-C": createProfile({
    strategySummary: "Piratencrew mit moeglichem undead Caribbean-Vibe. Opportunistisch, frech und bereit fuer schmutzige Vorteile.",
    buyStyle: "Kauft mobile raiders, trickster und seadog-Fits.",
    sellStyle: "Verkauft teure Landratten ohne Crew-Fit schnell.",
    contractStyle: "Kurz bis mittel, viel Beweglichkeit.",
    rosterStyle: "Wendige opportunistische Crew statt starre Struktur.",
    preferredArchetypes: ["pirate", "raider", "corsair", "undead sailor"],
    avoidedArchetypes: ["rigid knight"],
    hardNoGos: ["authority-loving hall monitor"],
    bias: {
      cashPriority: 6,
      valuePriority: 7,
      starPriority: 5,
      riskTolerance: 7,
      wageSensitivity: 5,
      sellForProfitAggression: 7,
      shortContractPreference: 7,
      longContractPreference: 3,
      loyaltyBias: 4,
      harmonyStrictness: 5,
      rosterDepthPreference: 5,
      eliteSmallRosterPreference: 6,
    },
  }),
  "P-S": createProfile({
    strategySummary: "Ausgestossene mit mentaler Haerte. Kein anderes Zuhause, daher hohe Zaehigkeit und fast trotziges Durchhalten.",
    buyStyle: "Kauft unbreakable grinders und mentale Ausdauertypen.",
    sellStyle: "Verkauft Front-Runner und fragile Egos eher als echte Sturkoepfe.",
    contractStyle: "Bindet Kaempfer gern, wenn sie das Zuhause annehmen.",
    rosterStyle: "Zaeher, loyaler Kern mit Underworld-Spirit.",
    preferredArchetypes: ["outcast grinder", "mental tank", "no-quit veteran"],
    avoidedArchetypes: ["soft quitter"],
    hardNoGos: ["gives up under pressure"],
    bias: {
      cashPriority: 5,
      valuePriority: 6,
      starPriority: 5,
      riskTolerance: 6,
      wageSensitivity: 6,
      sellForProfitAggression: 3,
      shortContractPreference: 4,
      longContractPreference: 7,
      loyaltyBias: 9,
      harmonyStrictness: 7,
      rosterDepthPreference: 7,
      eliteSmallRosterPreference: 4,
    },
  }),
  "R-L": createProfile({
    strategySummary: "Groessere, chaotischere Beast-Version. Charger, Werewolves und Animals in maximaler Wildheit.",
    buyStyle: "Kauft explosive Animal- und Werewolf-Fits mit Chaospotenzial.",
    sellStyle: "Verkauft zaehmende Fehlfits und zu ordentliche Profiles schnell.",
    contractStyle: "Kurz bis mittel, weil Chaos dynamisch bleibt.",
    rosterStyle: "Wilder Druckkader mit hohem Volatilitaetsfaktor.",
    preferredArchetypes: ["werewolf", "charger", "animal bruiser", "chaos beast"],
    avoidedArchetypes: ["bureaucrat", "saintly support"],
    preferredRaces: ["beast", "animal"],
    hardNoGos: ["domesticated low-fire profile"],
    bias: {
      cashPriority: 4,
      valuePriority: 5,
      starPriority: 8,
      riskTolerance: 9,
      wageSensitivity: 4,
      sellForProfitAggression: 5,
      shortContractPreference: 6,
      longContractPreference: 4,
      loyaltyBias: 4,
      harmonyStrictness: 3,
      rosterDepthPreference: 5,
      eliteSmallRosterPreference: 7,
    },
  }),
  "S-S": createProfile({
    strategySummary: "Roboter, Androiden und synthetische Soldaten. Reproduzierbare Effizienz und saubere technische Passform.",
    buyStyle: "Kauft konstruktive, synthetische und systemtreue Spieler mit klarer Funktion.",
    sellStyle: "Verkauft organische Stilbrüche ohne Systemfit eher frueh.",
    contractStyle: "Pragmatisch, stabil, berechenbar.",
    rosterStyle: "Technischer Systemkader mit hoher Reproduzierbarkeit.",
    preferredArchetypes: ["android", "robot soldier", "construct guard", "cyber striker"],
    avoidedArchetypes: ["chaos mystic"],
    preferredRaces: ["construct", "android", "synthetic", "augmented"],
    hardNoGos: ["broken unreliable organic wildcard"],
    bias: {
      cashPriority: 5,
      valuePriority: 7,
      starPriority: 5,
      riskTolerance: 3,
      wageSensitivity: 6,
      sellForProfitAggression: 4,
      shortContractPreference: 4,
      longContractPreference: 6,
      loyaltyBias: 5,
      harmonyStrictness: 8,
      rosterDepthPreference: 6,
      eliteSmallRosterPreference: 5,
    },
  }),
  "T-C": createProfile({
    strategySummary: "Friedliche gute Kapelle. Schutz der Schwachen und sanfter Stil, aber nicht so missionarisch wie Golden Gladiators.",
    buyStyle: "Kauft gute, friedliche und schutzorientierte Fits mit Teamwaerme.",
    sellStyle: "Verkauft rohe Sadisten und harte Stilbrüche eher frueh.",
    contractStyle: "Passende Good-Fits gern langfristiger.",
    rosterStyle: "Warmer, geschlossener Kern mit sozialem Schutzfokus.",
    preferredArchetypes: ["healer", "guardian", "choir knight", "gentle leader"],
    avoidedArchetypes: ["blood zealot", "sadist"],
    hardNoGos: ["predatory locker-room presence"],
    bias: {
      cashPriority: 4,
      valuePriority: 5,
      starPriority: 6,
      riskTolerance: 3,
      wageSensitivity: 5,
      sellForProfitAggression: 3,
      shortContractPreference: 3,
      longContractPreference: 8,
      loyaltyBias: 8,
      harmonyStrictness: 9,
      rosterDepthPreference: 6,
      eliteSmallRosterPreference: 4,
    },
  }),
  "V-D": createProfile({
    strategySummary: "Wald-Amazonen, fast nur Frauen, gelegentlich Pets. Elegant, giftig und naturverbunden.",
    buyStyle: "Kauft Amazonen-, Wald- und feminine Speed/Social-Fits, Pets als Sidekicks.",
    sellStyle: "Verkauft plumpe Stilbrüche ohne Amazonen-Vibe eher frueh.",
    contractStyle: "Mittel, bei klaren Stilspielerinnen auch laenger.",
    rosterStyle: "Geschlossener Stil-Kader mit natuerlicher Eleganz.",
    preferredArchetypes: ["amazon", "huntress", "forest rogue", "pet handler"],
    avoidedArchetypes: ["heavy plated brute"],
    preferredRaces: ["nature", "elf", "beast"],
    hardNoGos: ["anti-forest bruiser mascot"],
    bias: {
      cashPriority: 4,
      valuePriority: 6,
      starPriority: 6,
      riskTolerance: 5,
      wageSensitivity: 5,
      sellForProfitAggression: 4,
      shortContractPreference: 4,
      longContractPreference: 6,
      loyaltyBias: 7,
      harmonyStrictness: 8,
      rosterDepthPreference: 5,
      eliteSmallRosterPreference: 6,
    },
  }),
  "V-W": createProfile({
    strategySummary: "Maskenhelden und Selbstjustiz-Vibe. Gutes Ziel, aber mit Bereitschaft, das Gesetz zu dehnen.",
    buyStyle: "Kauft duale Hero-/Vigilante-Fits, die sauber zwischen Alltag und Nachtmodus wechseln.",
    sellStyle: "Verkauft offen korrupte oder komplett unheroische Fehlfits eher frueh.",
    contractStyle: "Mittlere Stabilitaet fuer verlaessliche Nachtakteure.",
    rosterStyle: "Disziplinierter Core mit maskierter Flexibilitaet.",
    preferredArchetypes: ["vigilante", "masked hero", "bounty hunter", "night ranger"],
    avoidedArchetypes: ["public villain", "cowardly civilian"],
    hardNoGos: ["cannot carry double life pressure"],
    bias: {
      cashPriority: 5,
      valuePriority: 6,
      starPriority: 6,
      riskTolerance: 5,
      wageSensitivity: 5,
      sellForProfitAggression: 4,
      shortContractPreference: 4,
      longContractPreference: 6,
      loyaltyBias: 6,
      harmonyStrictness: 7,
      rosterDepthPreference: 6,
      eliteSmallRosterPreference: 5,
    },
  }),
  "Z-H": createProfile({
    strategySummary: "Underground Bottom-to-top Team. Will um jeden Preis gewinnen, startet aggressiv und akzeptiert Risiko oder Overpay.",
    buyStyle: "Kauft High-upside Spieler aggressiv und nimmt lieber Risiko als Mittelmass.",
    sellStyle: "Verkauft nur, wenn Upgrade oder Machtgewinn klar ist.",
    contractStyle: "Opportunistisch; bindet Difference-Maker, wenn der Sprung echt ist.",
    rosterStyle: "Aggressiver Aufstiegskader mit Sieg-um-jeden-Preis-Mentalitaet.",
    preferredArchetypes: ["upside bet", "lizard grinder", "clutch closer", "high variance star"],
    avoidedArchetypes: ["safe low ceiling filler"],
    hardNoGos: ["comfortable loser mindset"],
    bias: {
      cashPriority: 3,
      valuePriority: 4,
      starPriority: 9,
      riskTolerance: 10,
      wageSensitivity: 2,
      sellForProfitAggression: 5,
      shortContractPreference: 4,
      longContractPreference: 6,
      loyaltyBias: 4,
      harmonyStrictness: 4,
      rosterDepthPreference: 3,
      eliteSmallRosterPreference: 9,
    },
  }),
  "W-L": createProfile({
    strategySummary: "Fast nur Soeldner/Mercenary-Spieler. Identitaet entsteht ueber Kampf und Vertrag, nicht ueber Heimat.",
    buyStyle: "Kauft battle-ready mercenaries und harte Profis mit sofortigem Nutzen.",
    sellStyle: "Verkauft kalt, wenn der Vertrag oder die Leistung kippt.",
    contractStyle: "Kurz bis mittel, maximale Beweglichkeit.",
    rosterStyle: "Funktionaler Profikader mit wenig Sentimentalitaet.",
    preferredArchetypes: ["mercenary", "gun for hire", "battle veteran"],
    avoidedArchetypes: ["development pet project"],
    preferredClasses: ["Mercenary"],
    hardNoGos: ["low effort paycheck collector"],
    bias: {
      cashPriority: 6,
      valuePriority: 7,
      starPriority: 6,
      riskTolerance: 6,
      wageSensitivity: 6,
      sellForProfitAggression: 8,
      shortContractPreference: 8,
      longContractPreference: 2,
      loyaltyBias: 2,
      harmonyStrictness: 5,
      rosterDepthPreference: 6,
      eliteSmallRosterPreference: 6,
    },
  }),
  "V-V": createProfile({
    strategySummary: "Vikings als Klasse/Archetyp bevorzugt. Gute Allrounder und raue Frontmentalitaet sind wertvoll.",
    buyStyle: "Kauft Vikings, Raiders und robuste Allrounder mit Kampfgeist.",
    sellStyle: "Verkauft elegante, zu weiche Fehlfits eher frueh.",
    contractStyle: "Mittel bis lang fuer Kernraider.",
    rosterStyle: "Robuster Allround-Kader mit rauer Kultur.",
    preferredArchetypes: ["viking", "raider", "berserker allrounder"],
    avoidedArchetypes: ["court stylist"],
    preferredClasses: ["Viking"],
    hardNoGos: ["fearful frontliner"],
    bias: {
      cashPriority: 5,
      valuePriority: 6,
      starPriority: 7,
      riskTolerance: 6,
      wageSensitivity: 5,
      sellForProfitAggression: 4,
      shortContractPreference: 4,
      longContractPreference: 7,
      loyaltyBias: 7,
      harmonyStrictness: 6,
      rosterDepthPreference: 6,
      eliteSmallRosterPreference: 5,
    },
  }),
  "M-M": createProfile({
    strategySummary: "Aggressives Multi-Champion-Topteam. Opportunistisch, stars-first und gnadenlos gegen gegnerische Schwaechen.",
    buyStyle: "Kauft Stars und Exploit-Fits aggressiv, wenn sie den Titelhebel vergroessern.",
    sellStyle: "Verkauft Ueberfluessiges oder second-tier Stars fuer den naechsten Edge.",
    contractStyle: "Bindet echte Titeltraeger, dreht am Rest opportunistisch.",
    rosterStyle: "Championship-Core mit aggressiver Spitzenausrichtung.",
    preferredArchetypes: ["champion star", "closer", "two-way ace", "meta exploiter"],
    avoidedArchetypes: ["cute project"],
    hardNoGos: ["low ambition filler"],
    bias: {
      cashPriority: 3,
      valuePriority: 5,
      starPriority: 10,
      riskTolerance: 8,
      wageSensitivity: 3,
      sellForProfitAggression: 6,
      shortContractPreference: 4,
      longContractPreference: 7,
      loyaltyBias: 5,
      harmonyStrictness: 5,
      rosterDepthPreference: 4,
      eliteSmallRosterPreference: 9,
    },
  }),
};

export function createDefaultTeamStrategyProfile(team: Team, identity?: TeamIdentity | null): TeamStrategyProfile {
  const seeded = strategySeedsByTeamId[team.teamId];
  const fallbackIdentitySummary = identity
    ? `Numeric team DNA POW ${identity.pow}, SPE ${identity.spe}, MEN ${identity.men}, SOC ${identity.soc}.`
    : "Numeric team DNA available via team identity.";
  const seed = seeded ?? createProfile({ strategySummary: `Default strategy profile for ${team.name}. ${fallbackIdentitySummary}` });

  return normalizeStrategyProfile(team, identity ?? null, {
    teamId: team.teamId,
    ...seed,
  });
}

export function buildTeamStrategyProfileMap(
  teams: Team[],
  identities: TeamIdentity[],
  existing?: Record<string, TeamStrategyProfile> | null,
) {
  return Object.fromEntries(
    teams.map((team) => {
      const current = existing?.[team.teamId];
      const identity = identities.find((entry) => entry.teamId === team.teamId) ?? null;
      const defaults = createDefaultTeamStrategyProfile(team, identity);
      return [
        team.teamId,
        normalizeStrategyProfile(team, identity, {
          ...defaults,
          ...current,
          teamId: team.teamId,
          bias: {
            ...defaults.bias,
            ...(current?.bias ?? {}),
          },
        }),
      ];
    }),
  );
}

export function getTeamStrategyProfile(gameState: GameState, teamId: string) {
  const existing = gameState.seasonState.teamStrategyProfiles?.[teamId];
  if (existing) {
    return existing;
  }

  const team = gameState.teams.find((entry) => entry.teamId === teamId);
  const identity = gameState.teamIdentities.find((entry) => entry.teamId === teamId) ?? null;
  return team ? createDefaultTeamStrategyProfile(team, identity) : null;
}

export function withNormalizedTeamStrategyProfiles(gameState: GameState): GameState {
  return {
    ...gameState,
    seasonState: {
      ...gameState.seasonState,
      teamStrategyProfiles: buildTeamStrategyProfileMap(
        gameState.teams,
        gameState.teamIdentities,
        gameState.seasonState.teamStrategyProfiles,
      ),
    },
  };
}
