export const playerGeneratorAttributeKeys = [
  "power",
  "health",
  "determination",
  "stamina",
  "speed",
  "dexterity",
  "awareness",
  "intelligence",
  "will",
  "charisma",
  "spirit",
  "torment",
] as const;

export type PlayerGeneratorAttributeKey = (typeof playerGeneratorAttributeKeys)[number];

export const officialDisciplineWeightOrder = [
  "tdm",
  "mini-dm",
  "battlefield",
  "gewichtheben",
  "climbing",
  "staffel",
  "time-trial",
  "spurt",
  "tennis",
  "hockey",
  "showcase",
  "speed-schach",
  "takeshis-castle",
  "breaking",
  "wettessen",
  "basketball",
  "football",
  "eiskunstlauf",
  "fechten",
  "i-spy",
] as const;

export type OfficialDisciplineWeightId = (typeof officialDisciplineWeightOrder)[number];

export const officialDisciplineWeightLabels: Record<OfficialDisciplineWeightId, string> = {
  tdm: "TDM",
  "mini-dm": "Mini DM",
  battlefield: "Battlefield",
  gewichtheben: "Gewichtheben",
  climbing: "Climbing",
  staffel: "Staffel",
  "time-trial": "Time Trial",
  spurt: "Spurt",
  tennis: "Tennis",
  hockey: "Hockey",
  showcase: "Showcase",
  "speed-schach": "Schach",
  "takeshis-castle": "Takeshi",
  breaking: "Breaking",
  wettessen: "Wettessen",
  basketball: "Basketball",
  football: "Football",
  eiskunstlauf: "Eiskunst",
  fechten: "Fechten",
  "i-spy": "I Spy",
};

export const officialDisciplineWeightTable: Record<
  PlayerGeneratorAttributeKey,
  Record<OfficialDisciplineWeightId, number>
> = {
  power: {
    tdm: 28,
    "mini-dm": 16,
    battlefield: 10,
    gewichtheben: 28,
    climbing: 8,
    staffel: 0,
    "time-trial": 5,
    spurt: 10,
    tennis: 0,
    hockey: 18,
    showcase: 11,
    "speed-schach": 0,
    "takeshis-castle": 0,
    breaking: 10,
    wettessen: 0,
    basketball: 7,
    football: 6,
    eiskunstlauf: 0,
    fechten: 10,
    "i-spy": 0,
  },
  health: {
    tdm: 20,
    "mini-dm": 20,
    battlefield: 8,
    gewichtheben: 16,
    climbing: 10,
    staffel: 2,
    "time-trial": 0,
    spurt: 6,
    tennis: 0,
    hockey: 18,
    showcase: 3,
    "speed-schach": 0,
    "takeshis-castle": 4,
    breaking: 18,
    wettessen: 22,
    basketball: 0,
    football: 14,
    eiskunstlauf: 0,
    fechten: 4,
    "i-spy": 2,
  },
  determination: {
    tdm: 6,
    "mini-dm": 0,
    battlefield: 4,
    gewichtheben: 12,
    climbing: 16,
    staffel: 4,
    "time-trial": 0,
    spurt: 15,
    tennis: 6,
    hockey: 4,
    showcase: 14,
    "speed-schach": 14,
    "takeshis-castle": 18,
    breaking: 10,
    wettessen: 16,
    basketball: 0,
    football: 8,
    eiskunstlauf: 6,
    fechten: 6,
    "i-spy": 8,
  },
  stamina: {
    tdm: 14,
    "mini-dm": 16,
    battlefield: 4,
    gewichtheben: 2,
    climbing: 26,
    staffel: 16,
    "time-trial": 15,
    spurt: 4,
    tennis: 12,
    hockey: 10,
    showcase: 0,
    "speed-schach": 0,
    "takeshis-castle": 6,
    breaking: 8,
    wettessen: 22,
    basketball: 6,
    football: 6,
    eiskunstlauf: 0,
    fechten: 0,
    "i-spy": 0,
  },
  speed: {
    tdm: 0,
    "mini-dm": 0,
    battlefield: 0,
    gewichtheben: 6,
    climbing: 12,
    staffel: 24,
    "time-trial": 22,
    spurt: 18,
    tennis: 6,
    hockey: 12,
    showcase: 8,
    "speed-schach": 10,
    "takeshis-castle": 4,
    breaking: 0,
    wettessen: 0,
    basketball: 10,
    football: 0,
    eiskunstlauf: 10,
    fechten: 16,
    "i-spy": 8,
  },
  dexterity: {
    tdm: 0,
    "mini-dm": 10,
    battlefield: 0,
    gewichtheben: 6,
    climbing: 12,
    staffel: 8,
    "time-trial": 25,
    spurt: 12,
    tennis: 12,
    hockey: 4,
    showcase: 9,
    "speed-schach": 7,
    "takeshis-castle": 6,
    breaking: 2,
    wettessen: 0,
    basketball: 8,
    football: 0,
    eiskunstlauf: 18,
    fechten: 20,
    "i-spy": 8,
  },
  awareness: {
    tdm: 2,
    "mini-dm": 0,
    battlefield: 10,
    gewichtheben: 0,
    climbing: 8,
    staffel: 12,
    "time-trial": 12,
    spurt: 7,
    tennis: 20,
    hockey: 8,
    showcase: 0,
    "speed-schach": 21,
    "takeshis-castle": 8,
    breaking: 0,
    wettessen: 0,
    basketball: 14,
    football: 11,
    eiskunstlauf: 14,
    fechten: 15,
    "i-spy": 5,
  },
  intelligence: {
    tdm: 6,
    "mini-dm": 0,
    battlefield: 16,
    gewichtheben: 0,
    climbing: 0,
    staffel: 0,
    "time-trial": 18,
    spurt: 0,
    tennis: 22,
    hockey: 0,
    showcase: 10,
    "speed-schach": 28,
    "takeshis-castle": 11,
    breaking: 2,
    wettessen: 8,
    basketball: 16,
    football: 0,
    eiskunstlauf: 8,
    fechten: 4,
    "i-spy": 18,
  },
  will: {
    tdm: 0,
    "mini-dm": 14,
    battlefield: 0,
    gewichtheben: 7,
    climbing: 8,
    staffel: 8,
    "time-trial": 0,
    spurt: 14,
    tennis: 0,
    hockey: 4,
    showcase: 0,
    "speed-schach": 14,
    "takeshis-castle": 22,
    breaking: 28,
    wettessen: 26,
    basketball: 0,
    football: 10,
    eiskunstlauf: 0,
    fechten: 0,
    "i-spy": 12,
  },
  charisma: {
    tdm: 10,
    "mini-dm": 0,
    battlefield: 20,
    gewichtheben: 23,
    climbing: 0,
    staffel: 10,
    "time-trial": 0,
    spurt: 0,
    tennis: 4,
    hockey: 0,
    showcase: 27,
    "speed-schach": 6,
    "takeshis-castle": 14,
    breaking: 0,
    wettessen: 0,
    basketball: 11,
    football: 4,
    eiskunstlauf: 28,
    fechten: 0,
    "i-spy": 9,
  },
  spirit: {
    tdm: 12,
    "mini-dm": 0,
    battlefield: 16,
    gewichtheben: 0,
    climbing: 0,
    staffel: 16,
    "time-trial": 0,
    spurt: 0,
    tennis: 18,
    hockey: 12,
    showcase: 16,
    "speed-schach": 0,
    "takeshis-castle": 0,
    breaking: 0,
    wettessen: 0,
    basketball: 22,
    football: 25,
    eiskunstlauf: 16,
    fechten: 0,
    "i-spy": 13,
  },
  torment: {
    tdm: 2,
    "mini-dm": 24,
    battlefield: 12,
    gewichtheben: 0,
    climbing: 0,
    staffel: 0,
    "time-trial": 3,
    spurt: 14,
    tennis: 0,
    hockey: 10,
    showcase: 2,
    "speed-schach": 0,
    "takeshis-castle": 7,
    breaking: 22,
    wettessen: 6,
    basketball: 6,
    football: 16,
    eiskunstlauf: 0,
    fechten: 25,
    "i-spy": 17,
  },
};

export const officialDisciplineWeightMatrix: Record<
  OfficialDisciplineWeightId,
  Partial<Record<PlayerGeneratorAttributeKey, number>>
> = Object.fromEntries(
  officialDisciplineWeightOrder.map((disciplineId) => [
    disciplineId,
    Object.fromEntries(
      playerGeneratorAttributeKeys
        .map((attributeKey) => [attributeKey, officialDisciplineWeightTable[attributeKey][disciplineId]] as const)
        .filter(([, weight]) => weight > 0),
    ),
  ]),
) as Record<OfficialDisciplineWeightId, Partial<Record<PlayerGeneratorAttributeKey, number>>>;

export function hasOfficialDisciplineWeights(disciplineId: string) {
  return Boolean(officialDisciplineWeightMatrix[disciplineId as OfficialDisciplineWeightId]);
}
