import type { PlayerGeneratorArchetype, PlayerGeneratorAttributeName } from "@/lib/data/olyDataTypes";
import type { PlayerGeneratorAxisKey } from "@/lib/player-generator/player-generator-role-profiles";

export type PlayerGeneratorArchetypeConstraint = {
  label: string;
  identityKeywords: string[];
  preferredRaces: string[];
  allowedRaces: string[];
  disallowedRaces: string[];
  preferredClasses: string[];
  disallowedClasses: string[];
  preferredSubclasses: string[];
  preferredPositiveTraits: string[];
  preferredNegativeTraits: string[];
  attributeBias: Partial<Record<PlayerGeneratorAttributeName, number>>;
  axisBias: Record<PlayerGeneratorAxisKey, number>;
  validationRules: {
    requireIdentityHit?: boolean;
    requirePreferredSubclass?: boolean;
    blockOnDisallowedRace?: boolean;
    blockOnDisallowedClass?: boolean;
  };
};

export const playerGeneratorArchetypes: Record<PlayerGeneratorArchetype, PlayerGeneratorArchetypeConstraint> = {
  mage: {
    label: "Mage",
    identityKeywords: ["mage", "warlock", "cleric", "shaman", "angel", "succubus"],
    preferredRaces: ["Divine", "Elf", "Human", "Voidborn"],
    allowedRaces: ["Divine", "Elf", "Human", "Voidborn", "Alien", "Demon"],
    disallowedRaces: ["Animal", "Goblin", "Tauren"],
    preferredClasses: ["Mage", "Tactician", "Overseer", "Templar"],
    disallowedClasses: ["Sprinter"],
    preferredSubclasses: ["Mage", "Warlock", "Cleric", "Shaman", "Strategist"],
    preferredPositiveTraits: ["Disciplined", "Cool", "Resourceful", "Motivated"],
    preferredNegativeTraits: ["Obsessive", "Paranoid"],
    attributeBias: { intelligence: 10, will: 7, awareness: 6, spirit: 6, power: -4 },
    axisBias: { pow: -4, spe: 2, men: 14, soc: 4 },
    validationRules: { requireIdentityHit: false, blockOnDisallowedRace: true, blockOnDisallowedClass: true },
  },
  beast: {
    label: "Beast",
    identityKeywords: ["beast", "creature", "behemoth", "hunter", "jungle"],
    preferredRaces: ["Animal", "Orc", "Tauren", "Lizard", "Dragon", "Mutant"],
    allowedRaces: ["Animal", "Orc", "Tauren", "Lizard", "Dragon", "Mutant", "Goblin", "Plant"],
    disallowedRaces: ["Divine", "Dwarf"],
    preferredClasses: ["Berserker", "Tank", "Charger", "Warlord"],
    disallowedClasses: ["Bard"],
    preferredSubclasses: ["Beast", "Creature", "Behemoth", "Hunter", "Jungle"],
    preferredPositiveTraits: ["Fearless", "Healthy", "Motivated", "FiredUp"],
    preferredNegativeTraits: ["Feisty", "ColdBlooded"],
    attributeBias: { power: 10, health: 8, stamina: 6, intelligence: -6, charisma: -5 },
    axisBias: { pow: 16, spe: 6, men: -8, soc: -5 },
    validationRules: { requireIdentityHit: true, blockOnDisallowedRace: true, blockOnDisallowedClass: false },
  },
  rogue: {
    label: "Rogue",
    identityKeywords: ["rogue", "assassin", "ninja", "scout", "trickster", "spec-ops"],
    preferredRaces: ["Human", "Elf", "Alien", "Voidborn"],
    allowedRaces: ["Human", "Elf", "Alien", "Voidborn", "Demon", "Goblin"],
    disallowedRaces: ["Tauren"],
    preferredClasses: ["Rogue", "Sprinter", "Overseer"],
    disallowedClasses: ["Tank"],
    preferredSubclasses: ["Assassin", "Scout", "Trickster", "Spec Ops", "Ninja"],
    preferredPositiveTraits: ["Flexible", "Cool", "Resourceful"],
    preferredNegativeTraits: ["Devious", "Mercenary"],
    attributeBias: { speed: 10, dexterity: 10, awareness: 6, health: -5 },
    axisBias: { pow: -2, spe: 16, men: 6, soc: 2 },
    validationRules: { requireIdentityHit: false, blockOnDisallowedRace: true, blockOnDisallowedClass: true },
  },
  tank: {
    label: "Tank",
    identityKeywords: ["tank", "guardian", "knight", "behemoth", "warrior"],
    preferredRaces: ["Construct", "Orc", "Tauren", "Human", "Demon"],
    allowedRaces: ["Construct", "Orc", "Tauren", "Human", "Demon", "Lizard", "Dragon"],
    disallowedRaces: ["Gnom"],
    preferredClasses: ["Tank", "Templar", "Warlord"],
    disallowedClasses: ["Sprinter"],
    preferredSubclasses: ["Guardian", "Knight", "Warrior", "Behemoth", "Controller"],
    preferredPositiveTraits: ["Healthy", "Loyal", "Disciplined"],
    preferredNegativeTraits: ["Obsessive", "ColdBlooded"],
    attributeBias: { health: 10, stamina: 9, will: 7, speed: -6, charisma: -4 },
    axisBias: { pow: 16, spe: -8, men: 8, soc: -4 },
    validationRules: { requireIdentityHit: false, blockOnDisallowedRace: false, blockOnDisallowedClass: true },
  },
  warrior: {
    label: "Warrior",
    identityKeywords: ["warrior", "knight", "viking", "hunter"],
    preferredRaces: ["Human", "Orc", "Tauren", "Demon", "Construct"],
    allowedRaces: ["Human", "Orc", "Tauren", "Demon", "Construct", "Elf", "Lizard"],
    disallowedRaces: [],
    preferredClasses: ["Warlord", "Berserker", "Charger", "Templar"],
    disallowedClasses: [],
    preferredSubclasses: ["Warrior", "Knight", "Viking", "Hunter", "Guardian"],
    preferredPositiveTraits: ["Fearless", "Disciplined", "Motivated"],
    preferredNegativeTraits: ["Feisty", "Obsessive"],
    attributeBias: { power: 8, stamina: 6, determination: 5, spirit: -2 },
    axisBias: { pow: 12, spe: 5, men: 2, soc: 0 },
    validationRules: { requireIdentityHit: false, blockOnDisallowedRace: false, blockOnDisallowedClass: false },
  },
  social_icon: {
    label: "Social Icon",
    identityKeywords: ["ambassador", "hero", "bard", "royalty", "angel"],
    preferredRaces: ["Human", "Divine", "Elf", "Aqua"],
    allowedRaces: ["Human", "Divine", "Elf", "Aqua", "Alien"],
    disallowedRaces: ["Construct"],
    preferredClasses: ["Bard", "Hero", "Overseer"],
    disallowedClasses: ["Tank"],
    preferredSubclasses: ["Ambassador", "Hero", "Royalty", "Angel", "Cleric"],
    preferredPositiveTraits: ["Eloquent", "FanFavorite", "Caring", "Altruistic", "Loyal"],
    preferredNegativeTraits: ["Diva", "Scandalous", "Egomaniac"],
    attributeBias: { charisma: 12, spirit: 8, awareness: 5, torment: -5 },
    axisBias: { pow: -8, spe: 0, men: 6, soc: 18 },
    validationRules: { requireIdentityHit: false, blockOnDisallowedRace: true, blockOnDisallowedClass: true },
  },
  construct: {
    label: "Construct",
    identityKeywords: ["construct", "augmented", "bot", "engineer", "controller"],
    preferredRaces: ["Construct"],
    allowedRaces: ["Construct"],
    disallowedRaces: ["Animal", "Divine"],
    preferredClasses: ["Tank", "Overseer", "Tactician"],
    disallowedClasses: ["Bard"],
    preferredSubclasses: ["Augmented", "Bot", "Engineer", "Controller"],
    preferredPositiveTraits: ["Disciplined", "Resourceful", "Cool"],
    preferredNegativeTraits: ["ColdBlooded", "Obsessive", "Paranoid"],
    attributeBias: { health: 6, stamina: 8, will: 8, awareness: 6, spirit: -8, charisma: -6 },
    axisBias: { pow: 6, spe: -2, men: 12, soc: -8 },
    validationRules: { requireIdentityHit: true, requirePreferredSubclass: false, blockOnDisallowedRace: true, blockOnDisallowedClass: true },
  },
  undead: {
    label: "Undead",
    identityKeywords: ["undead", "vampire", "wraith", "apparition", "warlock"],
    preferredRaces: ["Voidborn", "Demon", "Construct"],
    allowedRaces: ["Voidborn", "Demon", "Construct", "Human", "Alien"],
    disallowedRaces: ["Dwarf", "Divine", "Animal", "Tauren", "Goblin", "Orc", "Gnom"],
    preferredClasses: ["Mage", "Overseer", "Templar", "Tank", "Tactician"],
    disallowedClasses: ["Bard", "Sprinter"],
    preferredSubclasses: ["Undead", "Vampire", "Wraith", "Apparition", "Warlock", "Knight", "Strategist"],
    preferredPositiveTraits: ["ColdBlooded", "Fearless", "Loyal", "Diligent", "Motivated"],
    preferredNegativeTraits: ["Obsessive", "Paranoid", "FaintHearted"],
    attributeBias: { will: 8, stamina: 7, intelligence: 8, awareness: 6, speed: -4, spirit: -2 },
    axisBias: { pow: 8, spe: -4, men: 12, soc: -6 },
    validationRules: { requireIdentityHit: true, requirePreferredSubclass: true, blockOnDisallowedRace: true, blockOnDisallowedClass: true },
  },
  nature: {
    label: "Nature",
    identityKeywords: ["druid", "shaman", "jungle", "beast", "creature"],
    preferredRaces: ["Elf", "Plant", "Animal", "Aqua", "Tauren"],
    allowedRaces: ["Elf", "Plant", "Animal", "Aqua", "Tauren", "Lizard", "Human"],
    disallowedRaces: ["Construct"],
    preferredClasses: ["Bard", "Hero", "Overseer", "Templar"],
    disallowedClasses: [],
    preferredSubclasses: ["Druid", "Shaman", "Jungle", "Creature", "Wayfarer"],
    preferredPositiveTraits: ["Caring", "Healthy", "Altruistic", "Flexible"],
    preferredNegativeTraits: ["Timid", "Obsessive"],
    attributeBias: { awareness: 8, spirit: 8, stamina: 5, torment: -5 },
    axisBias: { pow: 2, spe: 8, men: 8, soc: 8 },
    validationRules: { requireIdentityHit: false, blockOnDisallowedRace: true, blockOnDisallowedClass: false },
  },
  demon: {
    label: "Demon",
    identityKeywords: ["demon", "succubus", "prime-evil", "warlock", "fallen-angel"],
    preferredRaces: ["Demon"],
    allowedRaces: ["Demon", "Voidborn", "Human"],
    disallowedRaces: ["Divine"],
    preferredClasses: ["Badass", "Mage", "Overseer", "Berserker"],
    disallowedClasses: [],
    preferredSubclasses: ["Succubus", "Prime Evil", "Warlock", "Fallen Angel", "Maniac"],
    preferredPositiveTraits: ["Fearless", "FiredUp", "Resourceful"],
    preferredNegativeTraits: ["ColdBlooded", "Scandalous", "Renegade"],
    attributeBias: { torment: 10, charisma: 6, power: 6, spirit: -4 },
    axisBias: { pow: 12, spe: 4, men: 0, soc: 8 },
    validationRules: { requireIdentityHit: true, blockOnDisallowedRace: true, blockOnDisallowedClass: false },
  },
  angel: {
    label: "Angel",
    identityKeywords: ["angel", "fallen-angel", "cleric", "god"],
    preferredRaces: ["Divine"],
    allowedRaces: ["Divine", "Human", "Elf"],
    disallowedRaces: ["Demon"],
    preferredClasses: ["Templar", "Hero", "Bard", "Mage"],
    disallowedClasses: [],
    preferredSubclasses: ["Angel", "Fallen Angel", "Cleric", "God", "Servant"],
    preferredPositiveTraits: ["Altruistic", "Caring", "Loyal", "Motivated", "Disciplined"],
    preferredNegativeTraits: ["Timid", "FaintHearted"],
    attributeBias: { spirit: 10, charisma: 8, will: 7, torment: -8 },
    axisBias: { pow: 2, spe: 4, men: 8, soc: 14 },
    validationRules: { requireIdentityHit: true, blockOnDisallowedRace: true, blockOnDisallowedClass: false },
  },
  pirate: {
    label: "Pirate",
    identityKeywords: ["pirate", "swashbuckler", "rebel", "vigilante"],
    preferredRaces: ["Human", "Aqua", "Demon"],
    allowedRaces: ["Human", "Aqua", "Demon", "Elf", "Alien"],
    disallowedRaces: ["Construct"],
    preferredClasses: ["Rogue", "Bard", "Sprinter", "Warlord"],
    disallowedClasses: [],
    preferredSubclasses: ["Pirate", "Swashbuckler", "Rebel", "Vigilante", "Scout"],
    preferredPositiveTraits: ["Flexible", "FanFavorite", "Cool", "Resourceful"],
    preferredNegativeTraits: ["Mercenary", "Scandalous", "Gambler"],
    attributeBias: { dexterity: 6, charisma: 8, awareness: 5, will: -2 },
    axisBias: { pow: 6, spe: 8, men: -2, soc: 12 },
    validationRules: { requireIdentityHit: true, blockOnDisallowedRace: true, blockOnDisallowedClass: false },
  },
  ninja: {
    label: "Ninja",
    identityKeywords: ["ninja", "assassin", "spec-ops", "shadow"],
    preferredRaces: ["Human", "Elf", "Alien", "Voidborn"],
    allowedRaces: ["Human", "Elf", "Alien", "Voidborn", "Demon"],
    disallowedRaces: ["Tauren"],
    preferredClasses: ["Rogue", "Sprinter", "Overseer"],
    disallowedClasses: ["Tank"],
    preferredSubclasses: ["Ninja", "Assassin", "Spec Ops", "Scout", "Trickster"],
    preferredPositiveTraits: ["Disciplined", "Flexible", "Cool"],
    preferredNegativeTraits: ["Devious", "ColdBlooded"],
    attributeBias: { speed: 10, dexterity: 10, awareness: 8, health: -6 },
    axisBias: { pow: -2, spe: 18, men: 6, soc: -2 },
    validationRules: { requireIdentityHit: true, blockOnDisallowedRace: true, blockOnDisallowedClass: true },
  },
  mercenary: {
    label: "Mercenary",
    identityKeywords: ["mercenary", "rebel", "spec-ops", "warrior"],
    preferredRaces: ["Human", "Orc", "Demon", "Construct"],
    allowedRaces: ["Human", "Orc", "Demon", "Construct", "Alien", "Tauren"],
    disallowedRaces: [],
    preferredClasses: ["Warlord", "Charger", "Rogue", "Tank", "Overseer"],
    disallowedClasses: [],
    preferredSubclasses: ["Spec Ops", "Rebel", "Warrior", "Hunter", "Executioner"],
    preferredPositiveTraits: ["Resourceful", "Disciplined", "Fearless"],
    preferredNegativeTraits: ["Mercenary", "Renegade", "Gambler"],
    attributeBias: { power: 6, speed: 5, determination: 5, charisma: 2 },
    axisBias: { pow: 10, spe: 8, men: 2, soc: 2 },
    validationRules: { requireIdentityHit: false, blockOnDisallowedRace: false, blockOnDisallowedClass: false },
  },
};

